ddcutil Internals: adl/adl_impl/adl_errors.c File Reference
adl_errors.c File Reference
#include "util/string_util.h"
#include "base/adl_errors.h"
#include "base/status_code_mgt.h"
Functions
Status_Code_Info * find_adl_status_description (Base_Status_ADL errnum)
Status_Code_Info * get_adl_status_description (Base_Status_ADL errnum)
bool adl_error_name_to_number (const char *adl_error_name, Base_Status_ADL *p_adl_error_number)
bool adl_error_name_to_modulated_number (const char *adl_error_name, Modulated_Status_ADL *p_adl_error_number)
Detailed Description
ADL Error Number Services
Definition in file adl_errors.c.
Function Documentation
bool adl_error_name_to_modulated_number (const char * adl_error_name, Modulated_Status_ADL * p_adl_error_number)
Gets the (modulated) ADL error number for a symbolic name.
Parameters
adl_error_name symbolic name, e.g. ADL_ERR_NOT_SUPPORTED
p_adl_error_number where to return error number
Returns
true if symbolic name found, false if not
Definition at line 163 of file adl_errors.c.
References adl_error_name_to_number(), modulate_rc(), and RR_ADL.
bool adl_error_name_to_number (const char * adl_error_name, Base_Status_ADL * p_adl_error_number)
Gets the (unmodulated) ADL error number for a symbolic name.
Parameters
adl_error_name symbolic name, e.g. ADL_ERR_NOT_SUPPORTED
p_adl_error_number where to return error number
Returns
true if symbolic name found, false if not
Definition at line 139 of file adl_errors.c.
References streq().
Referenced by adl_error_name_to_modulated_number().
Status_Code_Info* find_adl_status_description (Base_Status_ADL errnum)
Given an unmodulated ADL status code, return its Status_Code_Info struct.
Parameters
errnum unmodulated ADL status code
Returns
pointer to Status_Code_Info struct describing the code. NULL if code not found
Definition at line 79 of file adl_errors.c.
Referenced by get_adl_status_description().
Status_Code_Info* get_adl_status_description (Base_Status_ADL errnum)
Given an unmodulated ADL status code, return its Status_Code_Info struct.
If the error code is unrecognized, a dummy struct is initializaed and returmed. The contents of this struct are valid until the next call to this function.
Parameters
errnum unmodulated ADL status code
Returns
pointer to Status_Code_Info struct describing the code
Definition at line 103 of file adl_errors.c.
References find_adl_status_description(), and RR_ADL.