ddcutil Internals: adl/adl_impl/adl_intf.c File Reference
adl_intf.c File Reference
#include "util/device_id_util.h"
#include "util/report_util.h"
#include "util/string_util.h"
#include "base/ddc_packets.h"
#include "base/parms.h"
#include "base/sleep.h"
#include "adl/adl_impl/adl_friendly.h"
#include "adl/adl_impl/adl_report.h"
#include "adl/adl_impl/adl_sdk_includes.h"
#include "adl/adl_impl/adl_intf.h"
Functions
bool adl_is_available ()
bool adl_initialize ()
void adl_release ()
Parsed_Edid * adl_get_parsed_edid_by_adlno (int iAdapterIndex, int iDisplayIndex)
void adl_report_active_display (ADL_Display_Rec *pdisp, int depth)
void adl_report_active_display_by_index (int ndx, int depth)
int adl_report_active_displays ()
Display_Info_List adl_get_valid_displays ()
Base_Status_ADL adl_get_video_card_info_by_adlno (int iAdapterIndex, int iDisplayIndex, Video_Card_Info *card_info)
ADL_Display_Rec * adl_get_display_by_adlno (int iAdapterIndex, int iDisplayIndex, bool emit_error_msg)
ADL_Display_Rec * adl_find_display_by_mfg_model_sn (const char *mfg_id, const char *model, const char *sn)
ADL_Display_Rec * adl_find_display_by_edid (const Byte *pEdidBytes)
bool adl_is_valid_adlno (int iAdapterIndex, int iDisplayIndex, bool emit_error_msg)
Base_Status_ADL call_ADL_Display_DDCBlockAccess_Get (int iAdapterIndex, int iDisplayIndex, int iOption, int iCommandIndex, int iSendMsgLen, char *lpucSendMsgBuf, int *iRecvMsgLen, char *lpucRcvMsgBuf)
Base_Status_ADL adl_ddc_write_only (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen)
Base_Status_ADL adl_ddc_read_only (int iAdapterIndex, int iDisplayIndex, Byte *pRcvMsgBuf, int *pRcvBytect)
Base_Status_ADL adl_ddc_write_read (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen, Byte *pRcvMsgBuf, int *pRcvBytect)
Base_Status_ADL adl_ddc_write_read_onecall (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen, Byte *pRcvMsgBuf, int *pRcvBytect)
Function Documentation
Base_Status_ADL adl_ddc_read_only (int iAdapterIndex, int iDisplayIndex, Byte * pRcvMsgBuf, int * pRcvBytect)
Reads a DDC packet from the specified ADL display
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADL display number
pRcvMsgBuf pointer to buffer in which to return packet
pRcvBytect pointer to integer in which packet length returned
Returns
ADL status code
Definition at line 1107 of file adl_intf.c.
References call_ADL_Display_DDCBlockAccess_Get(), and hexstring().
Referenced by adl_ddc_write_read(), and adlshim_ddc_read_only().
Base_Status_ADL adl_ddc_write_only (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen)
Writes a DDC packet to the specified ADL display
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADL display number
pSendMsgBuf pointer to bytes to write
sendMsgLen number of bytes to write
Returns
ADL status code
Remarks
10/2015: called locally and from ddc_packet_io.c
Definition at line 1077 of file adl_intf.c.
References call_ADL_Display_DDCBlockAccess_Get().
Referenced by adl_ddc_set_vcp(), adl_ddc_write_only_with_retry(), adl_ddc_write_read(), and adlshim_ddc_write_only().
Base_Status_ADL adl_ddc_write_read (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen, Byte * pRcvMsgBuf, int * pRcvBytect)
Performs and DDC write followed by a DDC read.
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADL display number
pSendMsgBuf buffer containing bytes to send
sendMsgLen number of bytes to send
pRcvMsgBuf where to return bytes read
pRcvBytect where to return number of bytes read
Returns
ADL status code
Remarks
10/2015: called from adl_services.c and ddc_packet_io.c
Definition at line 1156 of file adl_intf.c.
References adl_ddc_read_only(), adl_ddc_write_only(), and hexstring().
Referenced by adl_ddc_get_vcp(), and adl_ddc_write_read_with_retry().
Base_Status_ADL adl_ddc_write_read_onecall (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen, Byte * pRcvMsgBuf, int * pRcvBytect)
Attempts to perform a DDC write followed by a DDC read using a single call to ADL_Display_DDCBlockAccess_Get(().
However, appears to just return the bytes written.
DO NOT USE
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADL display number
pSendMsgBuf buffer containing bytes to send
sendMsgLen number of bytes to send
pRcvMsgBuf where to return bytes read
pRcvBytect where to return number of bytes read
Returns
ADL status code
Remarks
10/2015: only called in adl_aux_intf.c
Definition at line 1210 of file adl_intf.c.
References call_ADL_Display_DDCBlockAccess_Get(), and hexstring().
Referenced by adl_ddc_get_vcp(), and adl_ddc_write_read_with_retry_onecall().
ADL_Display_Rec* adl_find_display_by_edid (const Byte * pEdidBytes)
Finds ADL display by EDID
Parameters
pEdidBytes pointer to 128 byte EDID
Returns
pointer to ADL_Display_Rec describing the display, NULL if not found
Definition at line 961 of file adl_intf.c.
Referenced by adlshim_find_display_by_edid().
ADL_Display_Rec* adl_find_display_by_mfg_model_sn (const char * mfg_id, const char * model, const char * sn)
Finds ADL display by some combination of manufacturer id, model name and serial number
Parameters
mfg_id 3 character manufacturer id
model model name string
sn serial number string
Returns
pointer to ADL_Display_Rec describing the display, NULL if not found
Definition at line 908 of file adl_intf.c.
References streq().
Referenced by adlshim_find_display_by_mfg_model_sn().
ADL_Display_Rec* adl_get_display_by_adlno (int iAdapterIndex, int iDisplayIndex, bool emit_error_msg)
Finds ADL display by adapter number/display number
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADLdisplay number
emit_error_msg if true, emit messages for errors
Returns
pointer to ADL_Display_Rec describing the display, NULL if not found
Definition at line 868 of file adl_intf.c.
References f0printf(), and FERR.
Referenced by adl_get_parsed_edid_by_adlno(), adl_get_video_card_info_by_adlno(), adl_is_valid_adlno(), and adl_report_active_display_by_index().
Parsed_Edid* adl_get_parsed_edid_by_adlno (int iAdapterIndex, int iDisplayIndex)
Returns a Parsed_Edid for an ADL display
Parameters
iAdapterIndex adapter number
iDisplayIndex display number
Returns
pointer to Parsed_Edid, NULL if display not found
Definition at line 602 of file adl_intf.c.
References adl_get_display_by_adlno(), adl_get_parsed_edid_by_adlno(), Parsed_Edid::bytes, Parsed_Edid::mfg_id, Parsed_Edid::model_name, and Parsed_Edid::serial_ascii.
Referenced by adl_get_parsed_edid_by_adlno(), adlshim_get_parsed_edid_by_display_handle(), and adlshim_get_parsed_edid_by_display_ref().
Display_Info_List adl_get_valid_displays ()
Returns a Display_Info_List describing the detected ADL displays.
Returns
Display_Info_List
Definition at line 741 of file adl_intf.c.
References rpt_int(), rpt_str(), and rpt_structure_loc().
Referenced by adlshim_get_valid_displays().
Base_Status_ADL adl_get_video_card_info_by_adlno (int iAdapterIndex, int iDisplayIndex, Video_Card_Info * card_info)
Gets video card information for the specified adapter number/display number pair.
Parameters
iAdapterIndex adapter number
iDisplayIndex display number
card_info pointer to existing Video_Card_Info struct where information is returned
Returns
ADL status code
Todo:
A pointer to a newly allocated string for the adapter name is returned in card_info. This is a memory leak.
Definition at line 830 of file adl_intf.c.
References adl_get_display_by_adlno(), and PROGRAM_LOGIC_ERROR.
Referenced by adlshim_get_video_card_info().
bool adl_initialize ()
This is the main function for initializing the ADL environment.
Must be called before any function other than is_adl_available().
It is not an error if this function is called multiple times.
Performs the following steps:
checks if ADL tracing is in effect
dynamically links the ADL library
initializes the framework
scans for ADL monitors
Return values
true if initialization succeeded, or already initialized
false initialization failed
Returns: true if initialization successful, false if not
Definition at line 545 of file adl_intf.c.
Referenced by adlshim_initialize().
bool adl_is_available ()
Checks if the ADL environment has been initialized.
Returns
true/false
Definition at line 136 of file adl_intf.c.
References create_parsed_edid(), Parsed_Edid::mfg_id, Parsed_Edid::model_name, and Parsed_Edid::serial_ascii.
Referenced by adlshim_is_available().
bool adl_is_valid_adlno (int iAdapterIndex, int iDisplayIndex, bool emit_error_msg)
Verifies that an (adapter number,display number) pair specifies an active ADL display
Parameters
iAdapterIndex ADL adapter number
iDisplayIndex ADL display number
emit_error_msg if true, emit error messages
Returns
true if an active display, false if not
Definition at line 990 of file adl_intf.c.
References adl_get_display_by_adlno().
Referenced by adlshim_is_valid_display_ref().
void adl_release ()
Releases the ADL framework
Definition at line 577 of file adl_intf.c.
Referenced by adlshim_initialize().
void adl_report_active_display (ADL_Display_Rec * pdisp, int depth)
Describes a display, specified by a pointer to its ADL_Display_Rec, using report functions.
Output is written to the currently active report destination.
Parameters
pdisp points to ADL_Display_Rec for the display
depth logical indentation depth
Definition at line 644 of file adl_intf.c.
References devid_ensure_initialized(), devid_get_pci_names(), get_output_level(), OL_NORMAL, OL_TERSE, OL_VERBOSE, report_parsed_edid(), rpt_vstring(), and Pci_Usb_Id_Names::vendor_name.
Referenced by adl_report_active_display_by_index(), and adl_report_active_displays().
void adl_report_active_display_by_index (int ndx, int depth)
Describes a display, specified by its index in the list of displays, using report functions.
Output is written to the currently active report destination.
Parameters
ndx index into array of active ADL displays
depth logical indentation depth
Definition at line 681 of file adl_intf.c.
References adl_get_display_by_adlno(), adl_report_active_display(), and rpt_vstring().
int adl_report_active_displays ()
Show information about attached ADL displays.
Output is written using report functions.
Returns
number of active displays
Definition at line 719 of file adl_intf.c.
References adl_report_active_display(), and rpt_vstring().
Base_Status_ADL call_ADL_Display_DDCBlockAccess_Get (int iAdapterIndex, int iDisplayIndex, int iOption, int iCommandIndex, int iSendMsgLen, char * lpucSendMsgBuf, int * iRecvMsgLen, char * lpucRcvMsgBuf)
Wrapper for ADL_Display_DDCBlockAccess_Get().
Used locally and in ADL tests
Definition at line 1013 of file adl_intf.c.
References hexstring().
Referenced by adl_ddc_read_only(), adl_ddc_write_only(), and adl_ddc_write_read_onecall().