ddcutil Internals: adl/adl_shim.h File Reference
adl_shim.h File Reference
#include "util/edid.h"
#include "base/core.h"
#include "base/displays.h"
#include "base/execution_stats.h"
#include "base/status_code_mgt.h"
Functions
bool adlshim_is_available ()
bool adlshim_initialize ()
Parsed_Edid * adlshim_get_parsed_edid_by_display_handle (Display_Handle *dh)
Parsed_Edid * adlshim_get_parsed_edid_by_display_ref (Display_Ref *dref)
void adlshim_report_active_display_by_display_ref (Display_Ref *dref, int depth)
bool adlshim_is_valid_display_ref (Display_Ref *dref, bool emit_error_msg)
Display_Ref * adlshim_find_display_by_mfg_model_sn (const char *mfg_id, const char *model, const char *sn)
Display_Ref * adlshim_find_display_by_edid (const Byte *pEdidBytes)
Display_Info_List adlshim_get_valid_displays ()
Modulated_Status_ADL adlshim_get_video_card_info (Display_Handle *dh, Video_Card_Info *card_info)
Global_Status_Code adlshim_ddc_write_only (Display_Handle *dh, Byte *pSendMsgBuf, int sendMsgLen)
Global_Status_Code adlshim_ddc_read_only (Display_Handle *dh, Byte *pRcvMsgBuf, int *pRcvBytect)
Detailed Description
Interface to ADL services
Will be implemented by either adl/adl_impl/adl_shim.c or adl/adl_mock_impl/adl_mock_shim.c
Definition in file adl_shim.h.
Function Documentation
Global_Status_Code adlshim_ddc_read_only (Display_Handle * dh, Byte * pRcvMsgBuf, int * pRcvBytect)
Issues a DDC read through ADL.
Parameters
dh display handle
pRcvMsgBuf pointer to buffer in which to return data read
pRcvBytect pointer to location where number of bytes read is stored
Returns
modulated ADL status code
Mock implementation to satisfy dynamic linker. Never called.
Definition at line 188 of file adl_shim.c.
References adl_ddc_read_only(), DDC_IO_ADL, modulate_rc(), and RR_ADL.
Global_Status_Code adlshim_ddc_write_only (Display_Handle * dh, Byte * pSendMsgBuf, int sendMsgLen)
Issues a DDC write through ADL.
Parameters
dh display handle
pSendMsgBuf pointer to bytes to send
sendMsgLen number of bytes to send
Returns
modulated ADL status code
Mock implementation to satisfy dynamic linker. Never called.
Definition at line 170 of file adl_shim.c.
References adl_ddc_write_only(), DDC_IO_ADL, modulate_rc(), and RR_ADL.
Display_Ref* adlshim_find_display_by_edid (const Byte * pEdidBytes)
Mock implementation to satisfy dynamic linker.
Parameters
pEdidBytes pointer to 128 byte EDID
Return values
NULL
Definition at line 128 of file adl_shim.c.
References adl_find_display_by_edid().
Display_Ref* adlshim_find_display_by_mfg_model_sn (const char * mfg_id, const char * model, const char * sn)
Mock implementation.
Return values
false
Definition at line 120 of file adl_shim.c.
References adl_find_display_by_mfg_model_sn().
Parsed_Edid* adlshim_get_parsed_edid_by_display_handle (Display_Handle * dh)
Mock implementation.
Return values
NULL
Definition at line 80 of file adl_shim.c.
References adl_get_parsed_edid_by_adlno(), and DDC_IO_ADL.
Parsed_Edid* adlshim_get_parsed_edid_by_display_ref (Display_Ref * dref)
Mock implementation.
Return values
NULL
Definition at line 90 of file adl_shim.c.
References adl_get_parsed_edid_by_adlno(), and DDC_IO_ADL.
Display_Info_List adlshim_get_valid_displays ()
Mock implementation to satisfy dynamic linker.
Returns
empty list
Definition at line 136 of file adl_shim.c.
References adl_get_valid_displays().
Modulated_Status_ADL adlshim_get_video_card_info (Display_Handle * dh, Video_Card_Info * card_info)
Get video card information for an ADL display.
Parameters
dh display handle
card_info pointer to Video_Card_Info struct to be filled in
Returns
modulated ADL status code
Mock implementation to satisfy dynamic linker. Never called.
Definition at line 148 of file adl_shim.c.
References adl_get_video_card_info_by_adlno(), modulate_rc(), and RR_ADL.
bool adlshim_initialize ()
Initialize the ADL subsystem. Wrappers function adl_initialize().
Must be called before any other function (except adlshim_is_available()):
Return values
true success
false failure
Mock implementation of ADL Initialization. Always returns false to indicate failure.
Return values
false
Definition at line 67 of file adl_shim.c.
References adl_initialize(), and adl_release().
bool adlshim_is_available ()
Wrappers adl_intf function adl_is_available().
Returns
true if ADL interface has been initialized, false if not
Indicates if ADL support is available. Always returns false, since this is a mock implementation to satisfy the dynamic linker.
Return values
false
Definition at line 55 of file adl_shim.c.
References adl_is_available().
bool adlshim_is_valid_display_ref (Display_Ref * dref, bool emit_error_msg)
Mock implementation.
Return values
false
Definition at line 114 of file adl_shim.c.
References adl_is_valid_adlno(), and DDC_IO_ADL.
void adlshim_report_active_display_by_display_ref (Display_Ref * dref, int depth)
Mock implemention. Does nothing.
Definition at line 106 of file adl_shim.c.
References DDC_IO_ADL.