ddcutil Internals: adl/adl_impl/adl_aux_intf.c File Reference
adl_aux_intf.c File Reference
#include "util/string_util.h"
#include "base/ddc_packets.h"
#include "base/parms.h"
#include "base/sleep.h"
#include "adl/adl_impl/adl_friendly.h"
#include "adl/adl_impl/adl_intf.h"
#include "adl/adl_shim.h"
#include "adl/adl_impl/adl_aux_intf.h"
Functions
Base_Status_ADL adl_ddc_write_only_with_retry (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen)
Base_Status_ADL adl_ddc_write_read_with_retry (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen, Byte *pRcvMsgBuf, int *pRcvBytect)
Base_Status_ADL adl_ddc_write_read_with_retry_onecall (int iAdapterIndex, int iDisplayIndex, Byte *pSendMsgBuf, int sendMsgLen, Byte *pRcvMsgBuf, int *pRcvBytect)
Base_Status_ADL adl_ddc_get_vcp (int iAdapterIndex, int iDisplayIndex, Byte vcp_feature_code, bool onecall)
Base_Status_ADL adl_ddc_set_vcp (int iAdapterIndex, int iDisplayIndex, Byte vcp_feature_code, int newval)
Detailed Description
Functions in this file were originally part of adl_inf.c, but with code refactoring are now only called from tests.
Definition in file adl_aux_intf.c.
Function Documentation
Base_Status_ADL adl_ddc_get_vcp (int iAdapterIndex, int iDisplayIndex, Byte vcp_feature_code, bool onecall)
Remarks
10/2015: unused
Definition at line 179 of file adl_aux_intf.c.
References adl_ddc_write_read(), adl_ddc_write_read_onecall(), hex_dump(), and hexstring().
Base_Status_ADL adl_ddc_set_vcp (int iAdapterIndex, int iDisplayIndex, Byte vcp_feature_code, int newval)
Remarks
10/2015: only used in adl_tests.c
Definition at line 244 of file adl_aux_intf.c.
References adl_ddc_write_only().
Base_Status_ADL adl_ddc_write_only_with_retry (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen)
Remarks
10/2015: only used in adl_tests.c
Definition at line 53 of file adl_aux_intf.c.
References adl_ddc_write_only(), and hexstring().
Base_Status_ADL adl_ddc_write_read_with_retry (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen, Byte * pRcvMsgBuf, int * pRcvBytect)
Remarks
10/2015: only used in adl_tests.c
Definition at line 89 of file adl_aux_intf.c.
References adl_ddc_write_read(), and hexstring().
Base_Status_ADL adl_ddc_write_read_with_retry_onecall (int iAdapterIndex, int iDisplayIndex, Byte * pSendMsgBuf, int sendMsgLen, Byte * pRcvMsgBuf, int * pRcvBytect)
Remarks
10/2015: unused
Definition at line 128 of file adl_aux_intf.c.
References adl_ddc_write_read_onecall(), and hexstring().