ddcutil Internals: adl/adl_impl/adl_friendly.h File Reference
adl_friendly.h File Reference
#include "base/core.h"
#include "adl/adl_impl/adl_intf.h"
#include "adl/adl_impl/adl_sdk_includes.h"
Functions
int call_ADL_Display_DDCBlockAccess_Get (int iAdapterIndex, int iDisplayIndex, int iOption, int xxx, int iSendMsgLen, char *lpucSendMsgBuf, int *iRecvMsgLen, char *lpucRcvMsgBuf)
Detailed Description
Type definitions, function declarations, etc that should be private to adl_intf.c, but need to be visible to other ADL related files, particularly tests.
Definition in file adl_friendly.h.
Function Documentation
int call_ADL_Display_DDCBlockAccess_Get (int iAdapterIndex, int iDisplayIndex, int iOption, int iCommandIndex, int iSendMsgLen, char * lpucSendMsgBuf, int * iRecvMsgLen, char * lpucRcvMsgBuf)
Wrapper for ADL_Display_DDCBlockAccess_Get().
Used locally and in ADL tests
Definition at line 1013 of file adl_intf.c.
References hexstring().
Referenced by adl_ddc_read_only(), adl_ddc_write_only(), and adl_ddc_write_read_onecall().