ddcutil Internals: base/core.h File Reference
core.h File Reference
#include "public/ddcutil_types.h"
#include "util/coredefs.h"
Macros
#define CALLOPT_NONE 0x00
no options
#define CALLOPT_ERR_MSG 0x80
issue message if error
#define CALLOPT_ERR_ABORT 0x40
terminate execution if error
#define CALLOPT_RDONLY 0x20
open read-only
#define CALLOPT_WARN_FINDEX 0x10
issue warning msg re hiddev_field_info.field_index change
#define CALLOPT_FORCE 0x08
ignore various validity checks
#define PROGRAM_LOGIC_ERROR(format, ...) program_logic_error(__func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
#define TERMINATE_EXECUTION_ON_ERROR(format, ...) terminate_execution_on_error(TRACE_GROUP, __func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
Typedefs
typedef Byte Call_Options
Functions
void init_msg_control ()
void register_jmp_buf (jmp_buf *jb)
void ddc_abort (const char *funcname, const int lineno, const char *fn, int status)
char * interpret_call_options (Call_Options calloptions)
void set_fout (FILE *fout)
void set_ferr (FILE *ferr)
void set_fout_to_default ()
void set_ferr_to_default ()
DDCA_Output_Level get_output_level ()
void set_output_level (DDCA_Output_Level newval)
char * output_level_name (DDCA_Output_Level val)
Trace_Group trace_class_name_to_value (char *name)
void set_trace_levels (Trace_Group trace_flags)
bool is_tracing (Trace_Group trace_group, const char *filename)
void program_logic_error (const char *funcname, const int lineno, const char *fn, char *format,...)
void terminate_execution_on_error (Trace_Group trace_group, const char *funcname, const int lineno, const char *fn, char *format,...)
Variables
bool dbgtrc_show_time
include elapsed time in debug/trace output
FILE * FOUT
FILE * FERR
Typedef Documentation
typedef Byte Call_Options
Byte of standard call options
Definition at line 95 of file core.h.
Function Documentation
char* interpret_call_options (Call_Options calloptions)
Interprets a Call_Options byte as a printable string. The returned value is valid until the next call of this function.
Parameters
calloptions Call_Options byte
Returns
interpreted value
Definition at line 379 of file core.c.
References f0printf(), FOUT, and vnt_interpret_flags().
bool is_tracing (Trace_Group trace_group, const char * filename)
Checks if a group is being traced
Parameters
trace_group group to check
filename file from which check is occurring (not currently used)
Returns
true if tracing enabled, false if not
Remarks
Multiple trace group bits can be set in trace_group. If any of those group are currently being traced, the function returns true. That is, a given trace location in the code can be activated by multiple trace groups.
If trace_group == TRC_ALWAYS (0xff), the function returns true. Commonly, if debugging is active in a given location, the trace_group value being checked can be set to TRC_ALWAYS, so a site can have a single debug/trace function call.
Definition at line 601 of file core.c.
References bool_repr(), dbgtrc_show_time, ddc_abort(), f0printf(), f0puts(), FERR, formatted_elapsed_time(), FOUT, is_tracing(), show_output_level(), and vnt_interpret_flags().
Referenced by is_tracing(), and terminate_execution_on_error().
void set_trace_levels (Trace_Group trace_flags)
Specify the trace groups to be traced.
Parameters
trace_flags bit flags indicating groups to trace
Definition at line 575 of file core.c.
Trace_Group trace_class_name_to_value (char * name)
Given a trace group name, return its identifier. Case is ignored.
Parameters
name trace group name
Returns
trace group identifier
Return values
TRC_NEVER unrecognized name
/ingroup dbgtrace
Definition at line 552 of file core.c.
References vnt_find_id().