ddcutil Internals: util/data_structures.c File Reference
data_structures.c File Reference
#include "string_util.h"
#include "data_structures.h"
Functions
Byte_Value_Array bva_create ()
int bva_length (Byte_Value_Array bva)
void bva_append (Byte_Value_Array bva, Byte item)
Byte bva_get (Byte_Value_Array bva, int ndx)
bool bva_contains (Byte_Value_Array bva, Byte item)
Byte * bva_bytes (Byte_Value_Array bva)
void bva_free (Byte_Value_Array bva)
void bva_report (Byte_Value_Array bva, char *title)
Byte_Bit_Flags bbf_create ()
void bbf_free (Byte_Bit_Flags bbflags)
void bbf_set (Byte_Bit_Flags bbflags, Byte val)
bool bbf_is_set (Byte_Bit_Flags bbflags, Byte val)
Byte_Bit_Flags bbf_subtract (Byte_Bit_Flags bbflags1, Byte_Bit_Flags bbflags2)
char * bbf_repr (Byte_Bit_Flags bbflags, char *buffer, int buflen)
int bbf_count_set (Byte_Bit_Flags bbflags)
char * bbf_to_string (Byte_Bit_Flags bbflags, char *buffer, int buflen)
Buffer * bbf_to_buffer (Byte_Bit_Flags bbflags)
bool store_bytehex_list (char *start, int len, void *data_struct, Byte_Appender appender)
bool bva_store_bytehex_list (Byte_Value_Array bva, char *start, int len)
bool bbf_store_bytehex_list (Byte_Bit_Flags bbf, char *start, int len)
Buffer * buffer_new (int size, const char *trace_msg)
void buffer_set_size_increment (Buffer *buf, uint16_t size_increment)
Buffer * buffer_new_with_value (Byte *bytes, int bytect, const char *trace_msg)
Buffer * buffer_dup (Buffer *srcbuf, const char *trace_msg)
void buffer_free (Buffer *buffer, const char *trace_msg)
int buffer_length (Buffer *buffer)
void buffer_set_length (Buffer *buffer, int bytect)
void buffer_put (Buffer *buffer, Byte *bytes, int bytect)
void buffer_set_byte (Buffer *buf, int offset, Byte byte)
void buffer_set_bytes (Buffer *buf, int offset, Byte *bytes, int bytect)
void buffer_append (Buffer *buffer, Byte *bytes, int bytect)
void buffer_strcat (Buffer *buffer, char *str)
void buffer_add (Buffer *buffer, Byte byte)
bool buffer_eq (Buffer *buf1, Buffer *buf2)
void buffer_extend (Buffer *buf, int addl_size)
void buffer_dump (Buffer *buffer)
char * vnt_name (Value_Name_Title *table, uint32_t val)
char * vnt_title (Value_Name_Title *table, uint32_t val)
uint32_t vnt_find_id (Value_Name_Title_Table table, const char *s, bool use_title, bool ignore_case, uint32_t default_id)
char * vnt_interpret_flags (uint32_t flags_val, Value_Name_Title_Table bitname_table, bool use_title, char *sepstr)
void vnt_debug_table (Value_Name_Title *table)
Detailed Description
Generic data structures
Definition in file data_structures.c.
Function Documentation
int bbf_count_set (Byte_Bit_Flags bbflags)
Returns the number of bits set in a Byte_Bit_Flags
Parameters
bbflags instance handle
Returns
number of bits set (0..256)
Definition at line 353 of file data_structures.c.
Referenced by bbf_to_buffer(), and bbf_to_string().
Byte_Bit_Flags bbf_create ()
Creates a new Byte_Bit_Flags instance.
Returns
opaque handle to new instance
Definition at line 237 of file data_structures.c.
Referenced by bbf_subtract().
void bbf_free (Byte_Bit_Flags bbflags)
Destroys a Byte_Bit_Flags instance.
Parameters
bbflags instance handle
Definition at line 246 of file data_structures.c.
bool bbf_is_set (Byte_Bit_Flags bbflags, Byte val)
Tests if a flag is set in a Byte_Bit_Flags instance.
Parameters
bbflags instance handle
val number of bit to test
Returns
true/false
Definition at line 279 of file data_structures.c.
Referenced by bbf_to_buffer(), and bbf_to_string().
char* bbf_repr (Byte_Bit_Flags bbflags, char * buffer, int buflen)
Returns a 64 character long hex string representing the data structure.
Parameters
bbflags instance handle
buffer buffer in which to return string
buflen buffer length
Returns
character string representation of flags that are set
If buffer is NULL then memory is malloc'd. It is the responsibility of the caller to free the returned string.
If buflen is insufficiently large an assertion fails.
Remarks
Future enhancement: Insert a separator character every n characters?
Definition at line 332 of file data_structures.c.
void bbf_set (Byte_Bit_Flags bbflags, Byte val)
Sets a flag in a Byte_Bit_Flags instance.
Parameters
bbflags instance handle
val number of bit to set
Definition at line 261 of file data_structures.c.
Referenced by bbf_to_buffer().
bool bbf_store_bytehex_list (Byte_Bit_Flags bbf, char * start, int len)
Parses a list of bytehex values and stores the result in a Byte_Bit_Flags.
Parameters
bbf handle of Byte_Bit_Flags instance
start starting address of hex values
len length of hex values
Returns
false if any input data cannot be parsed, true otherwise
Definition at line 554 of file data_structures.c.
References store_bytehex_list().
Byte_Bit_Flags bbf_subtract (Byte_Bit_Flags bbflags1, Byte_Bit_Flags bbflags2)
Subtracts one Byte_Bit_Flags instance from another. A flag is set in the result if it is set in the first instance but not in the second instance.
Parameters
bbflags1 handle to first instance
bbflags2 handle to second instance
Returns
newly created instance with the result
Definition at line 302 of file data_structures.c.
References bbf_create().
Buffer* bbf_to_buffer (Byte_Bit_Flags bbflags)
Converts a Byte_Bit_Flags instance to a sequence of bytes whose values correspond to the bits that are set. The byte sequence is returned in a newly allocated Buffer.
Parameters
bbflags instance handle
Returns
pointer to newly allocated Buffer
Definition at line 431 of file data_structures.c.
References bbf_count_set(), bbf_is_set(), bbf_set(), buffer_add(), buffer_new(), bva_append(), and bva_contains().
char* bbf_to_string (Byte_Bit_Flags bbflags, char * buffer, int buflen)
Returns a string of space separated 2 character hex values representing the bits set in the Byte_Bit_Flag, e.g. "03 7F" if bits 0x03 and 0x7F are set
Parameters
bbflags instance handle
buffer pointer to buffer in which to return character string, if NULL malloc a new buffer
buflen buffer length
Returns
pointer to character string
If a new buffer is allocated, it is the responsibility of the caller to free the string returned.
For complete safety in case every bit is set, buflen should be >= 768. (2 chars for every bit (512), 255 separator characters, 1 terminating null) If buflen in insufficiently large to contain the result, an assertion fails.
Definition at line 389 of file data_structures.c.
References bbf_count_set(), and bbf_is_set().
void buffer_add (Buffer * buffer, Byte byte)
Appends a single byte to the current value in the buffer. The buffer length is updated.
Parameters
buffer pointer to Buffer instance
byte value to append
Todo:
Increase buffer size if necessary and size_increment > 0
Definition at line 813 of file data_structures.c.
References Buffer::buffer_size, Buffer::bytes, Buffer::len, and Buffer::marker.
Referenced by bbf_to_buffer().
void buffer_append (Buffer * buffer, Byte * bytes, int bytect)
Appends a sequence of bytes to the current contents of a Buffer. The buffer length is updated.
Parameters
buffer pointer to the Buffer object
bytes pointer to the bytes to be appended
bytect number of bytes to append
Definition at line 755 of file data_structures.c.
References buffer_extend(), Buffer::buffer_size, Buffer::bytes, Buffer::len, Buffer::marker, and Buffer::size_increment.
Referenced by buffer_strcat().
void buffer_dump (Buffer * buffer)
Displays all fields of the Buffer. This is a debugging function.
Parameters
buffer pointer to Buffer instance
Remarks
Output is written to stdout.
Definition at line 863 of file data_structures.c.
References Buffer::buffer_size, Buffer::bytes, hex_dump(), and Buffer::len.
Buffer* buffer_dup (Buffer * srcbuf, const char * trace_msg)
Copies a Buffer.
Parameters
srcbuf instance to copy
trace_msg optional trace message
Returns
newly allocated copy
Remarks
The contents of the newly allocated Buffer is identical to the original, but the maximum length and size increment are not. Is this an issue?
Not currently used. (3/2017)
Definition at line 636 of file data_structures.c.
References buffer_new_with_value(), Buffer::bytes, and Buffer::len.
bool buffer_eq (Buffer * buf1, Buffer * buf2)
Tests whether 2 Buffer instances have the same contents.
Parameters
buf1 pointer to first Buffer
buf2 pointer to second Buffer
Returns
true if contents are identical, false if not
Remarks
If both buf1==NULL and buf2==NULL, the result is true
Definition at line 830 of file data_structures.c.
References Buffer::bytes, and Buffer::len.
void buffer_extend (Buffer * buf, int addl_size)
Increases the size of a Buffer
Parameters
buf pointer to Buffer instance
addl_size number of additional bytes
Definition at line 848 of file data_structures.c.
References Buffer::buffer_size, and Buffer::bytes.
Referenced by buffer_append().
void buffer_free (Buffer * buffer, const char * trace_msg)
Frees a Buffer instance. All memory associated with the Buffer is released.
Parameters
buffer pointer to Buffer instance, must be valid
trace_msg optional trace message
Definition at line 646 of file data_structures.c.
References Buffer::bytes, and Buffer::marker.
int buffer_length (Buffer * buffer)
Returns the length of the data in the Buffer.
Parameters
buffer pointer to Buffer instance
Returns
number of bytes in Buffer
Definition at line 672 of file data_structures.c.
References Buffer::len.
Buffer* buffer_new (int size, const char * trace_msg)
Allocates a Buffer instance
Parameters
size maximum number of bytes that buffer can hold
trace_msg optional trace message
Returns
pointer to newly allocated instance
Definition at line 575 of file data_structures.c.
References Buffer::buffer_size, Buffer::bytes, Buffer::len, Buffer::marker, and Buffer::size_increment.
Referenced by bbf_to_buffer(), and buffer_new_with_value().
Buffer* buffer_new_with_value (Byte * bytes, int bytect, const char * trace_msg)
Allocates a Buffer instance and sets an initial value
Parameters
bytes pointer to initial value
bytect length of initial value, the buffer size is also set to this value
trace_msg optional trace message
Returns
pointer to newly allocated instance
Remarks
Setting the buffer size to the initial value does not allow for expansion, unless buffer_set_size_increment() is called
Definition at line 616 of file data_structures.c.
References buffer_new(), and buffer_put().
Referenced by buffer_dup().
void buffer_put (Buffer * buffer, Byte * bytes, int bytect)
Sets the value stored in a Buffer to a range of bytes. The buffer length is updated.
Parameters
buffer pointer to Buffer instance
bytes pointer to bytes to store in buffer
bytect number of bytes to store
Definition at line 698 of file data_structures.c.
References Buffer::bytes, and Buffer::len.
Referenced by buffer_new_with_value().
void buffer_set_byte (Buffer * buf, int offset, Byte byte)
Stores a single byte at a specified offset in the buffer. The buffer length is not updated.
Parameters
buf pointer to Buffer instance
offset offset in buffer at which to store byte
byte byte value to be stored
Remarks
A dangerous function. Use with care.
Definition at line 722 of file data_structures.c.
References Buffer::bytes.
void buffer_set_bytes (Buffer * buf, int offset, Byte * bytes, int bytect)
Sets a range of bytes in a Buffer. The logical length of the buffer is not updated.
Parameters
buf pointer to Buffer instance
offset offset in buffer at which to store byte
bytes pointer to bytes to store
bytect number of bytes to store
Definition at line 738 of file data_structures.c.
References Buffer::buffer_size, and Buffer::bytes.
void buffer_set_length (Buffer * buffer, int bytect)
Adjusts the number of bytes in a Buffer.
Parameters
buffer pointer to buffer instance
bytect new length of buffer contents, must be less that the maximum size of the buffer
Definition at line 683 of file data_structures.c.
References Buffer::buffer_size, and Buffer::len.
Referenced by buffer_strcat().
void buffer_set_size_increment (Buffer * buf, uint16_t size_increment)
Sets a size increment for the buffer, allowing it to be dynamically resized if necessary.
Parameters
buf pointer to Buffer instance
size_increment if resizing is necessary, the buffer size will be increased by this amount
Definition at line 598 of file data_structures.c.
References Buffer::size_increment.
void buffer_strcat (Buffer * buffer, char * str)
Appends a string to the current string in the buffer.
Parameters
buffer pointer to Buffer
str string to append
Remarks
If the buffer is not empty, checks by assert that the last character stored is '\0';
Definition at line 792 of file data_structures.c.
References buffer_append(), buffer_set_length(), Buffer::bytes, Buffer::len, and Buffer::marker.
void bva_append (Byte_Value_Array bva, Byte item)
Adds a value to a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
item value to add
Definition at line 77 of file data_structures.c.
Referenced by bbf_to_buffer(), and bva_report().
Byte* bva_bytes (Byte_Value_Array bva)
Returns the bytes from a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
Returns
pointer to newly allocate memory containing bytes
Remarks
The length of the bytes returned must be obtained from bva_length(). Alternatively, consider returning a Buffer.
Definition at line 137 of file data_structures.c.
bool bva_contains (Byte_Value_Array bva, Byte item)
Checks if a Byte_Value_Array contains a value.
Parameters
bva Byte_Value_Array instance
item value to check for
Returns
true/false
Definition at line 109 of file data_structures.c.
Referenced by bbf_to_buffer().
Byte_Value_Array bva_create ()
Creates a new Byte_Value_Array instance.
Returns
newly allocated Byte_Value_Array.
Definition at line 55 of file data_structures.c.
Referenced by bva_report().
void bva_free (Byte_Value_Array bva)
Destroy a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
Definition at line 149 of file data_structures.c.
Referenced by bva_report().
Byte bva_get (Byte_Value_Array bva, int ndx)
Gets a value by its index from a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
ndx index of entry
Returns
value
ndx must be a valid value. The only check is by assert().
Definition at line 93 of file data_structures.c.
Referenced by bva_report().
int bva_length (Byte_Value_Array bva)
Returns the number of entries in a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
Returns
number of entries
Definition at line 66 of file data_structures.c.
Referenced by bva_report().
void bva_report (Byte_Value_Array bva, char * title)
Debugging function to report the contents of a Byte_Value_Array.
Parameters
bva Byte_Value_Array instance
title if non-null, line to print at start of report
Definition at line 160 of file data_structures.c.
References bva_append(), bva_create(), bva_free(), bva_get(), and bva_length().
bool bva_store_bytehex_list (Byte_Value_Array bva, char * start, int len)
Parses a list of bytehex values and stores the result in a Byte_Value_Array.
Parameters
bva handle of Byte_Value_Array instance
start starting address of hex values
len length of hex values
Returns
false if any input data cannot be parsed, true otherwise
Definition at line 541 of file data_structures.c.
References store_bytehex_list().
bool store_bytehex_list (char * start, int len, void * data_struct, Byte_Appender appender)
Stores a list of bytehex values in either a Byte_Value_Array or a Byte_Bit_Flags.
Parameters
start starting address of hex values
len length of hex values
data_struct opague handle to either a Byte_Value_Array or a Byte_Bit_Flags
appender function to add a value to data_struct
Returns
false if any input data cannot be parsed, true otherwise
Definition at line 488 of file data_structures.c.
References hhc_to_byte_in_buf().
Referenced by bbf_store_bytehex_list(), and bva_store_bytehex_list().
void vnt_debug_table (Value_Name_Title * table)
Shows the contents of a **Value_Name_Title table. Output is written to stdout.
Parameters
table pointer to table
Definition at line 1199 of file data_structures.c.
References Value_Name_Title::name, Value_Name_Title::title, and Value_Name_Title::value.
uint32_t vnt_find_id (Value_Name_Title_Table table, const char * s, bool use_title, bool ignore_case, uint32_t default_id)
Searches a Value_Name_Title_Table for a specified name or title, and returns its id value.
Parameters
table a Value_Name_Title table
s string to search for
use_title if false, search name field
if true, search title field
ignore_case if true, search is case-insensitive
default_id value to return if not found
Returns
value id
Definition at line 942 of file data_structures.c.
References Value_Name_Title::name, sbuf_append(), Value_Name_Title::title, Value_Name_Title::value, and vnt_find_id().
Referenced by trace_class_name_to_value(), and vnt_find_id().
char* vnt_interpret_flags (uint32_t flags_val, Value_Name_Title_Table bitname_table, bool use_title, char * sepstr)
Interprets an integer whose bits represent named flags.
Parameters
flags_val value to interpret
bitname_table pointer to Value_Name table
use_title if true, use the title field of the table,
if false, use the name field of the table
sepstr if non-NULL, separator string to insert between values
Returns
newly allocated character string
Remarks
It is the responsibility of the caller to free the returned string
If a referenced title field is NULL, "missing" is used as the value
Definition at line 1157 of file data_structures.c.
References Value_Name_Title::name, Value_Name_Title::title, and Value_Name_Title::value.
Referenced by connector_type_title(), ddc_abort(), interpret_call_options(), and is_tracing().
char* vnt_name (Value_Name_Title * table, uint32_t val)
Returns the name of an entry in a Value_Nmme_Title table.
Parameters
table pointer to table
val value to lookup
Returns
name of value, NULL if not found
Definition at line 889 of file data_structures.c.
References Value_Name_Title::name, and Value_Name_Title::value.
Referenced by connector_status_name(), connector_type_name(), and format_vcp_version_id().
char* vnt_title (Value_Name_Title * table, uint32_t val)
Returns the title (description field) of an entry in a Value_Nmme_Title table.
Parameters
table pointer to table
val value to lookup
Returns
title of value, NULL if not found
Definition at line 914 of file data_structures.c.
References Value_Name_Title::name, Value_Name_Title::title, and Value_Name_Title::value.
Referenced by connector_status_title(), connector_type_title(), encoder_type_title(), and format_vcp_version_id().