ddcutil Internals: base/ddc_errno.h File Reference
ddc_errno.h File Reference
#include "base/status_code_mgt.h"
Functions
Status_Code_Info * ddcrc_find_status_code_info (int rc)
bool ddc_error_name_to_number (const char *errno_name, Global_Status_Code *perrno)
bool ddc_error_name_to_modulated_number (const char *errno_name, Global_Status_Code *p_error_number)
bool ddcrc_is_derived_status_code (Global_Status_Code gsc)
bool ddcrc_is_not_error (Global_Status_Code gsc)
Detailed Description
Error codes internal to ddcutil.
Definition in file ddc_errno.h.
Function Documentation
bool ddc_error_name_to_modulated_number (const char * error_name, Global_Status_Code * p_errnum)
Gets the (modulated) ddcutil error number for a symbolic name.
Parameters
error_name symbolic name, e.g. DDCRC_CHECKSUM
p_errnum where to return error number
Returns: true if found, false if not
Remarks
Since ddcutil specific error numbers are always modulated, the return value for this function is always identical to ddc_error_name_to_number().
Definition at line 228 of file ddc_errno.c.
References ddc_error_name_to_number().
bool ddc_error_name_to_number (const char * error_name, Global_Status_Code * p_errnum)
Gets the (unmodulated) ddcutil error number for a symbolic name.
Parameters
error_name symbolic name, e.g. DDCRC_CHECKSUM
p_errnum where to return error number
Returns: true if found, false if not
Remarks
Since ddcutil specific error numbers are always modulated, the return value for this function is always identical to ddc_error_name_to_modulated_number().
Definition at line 203 of file ddc_errno.c.
References streq().
Referenced by ddc_error_name_to_modulated_number().
Status_Code_Info* ddcrc_find_status_code_info (int rc)
Returns the Status_Code_Info struct for a ddcutil status code.
Parameters
rc ddcutil status code
Returns
pointer to Status_Code_Info, NULL if not found
Remarks
Returns a pointer into a struct compiled into the executable. Do not deallocate.
ddcutil status codes are always modulated.
Definition at line 96 of file ddc_errno.c.
Referenced by ddcrc_is_not_error().
bool ddcrc_is_derived_status_code (Global_Status_Code gsc)
Certain ddcutil status codes (e.g. DDCRC_DETERMINED_UNSUPPORTED) are "derived" at higher levels from primary ddcutil status codes in lower level routines. These should be excluded from certain error counts as otherwise an error would be double counted.
Parameters
gsc status code
Returns
true/false
Definition at line 147 of file ddc_errno.c.
Referenced by log_status_code().
bool ddcrc_is_not_error (Global_Status_Code gsc)
Certain ddcutil status codes, (e.g. DDCRC_REPORTED_UNSUPPORTED) report states that should not be considered to be DDC protocol errors.
Definition at line 157 of file ddc_errno.c.
References ddcrc_find_status_code_info().
Referenced by log_status_code().