ddcutil Internals: util/device_id_util.h File Reference
device_id_util.h File Reference
Data Structures
struct Pci_Usb_Id_Names
Functions
bool devid_ensure_initialized ()
Pci_Usb_Id_Names devid_get_pci_names (ushort vendor_id, ushort device_id, ushort subvendor_id, ushort subdevice_id, int argct)
Pci_Usb_Id_Names devid_get_usb_names (ushort vendor_id, ushort device_id, ushort interface_id, int argct)
char * devid_hid_descriptor_item_type (ushort id)
char * devid_usage_code_page_name (ushort usage_page_code)
char * devid_usage_code_id_name (ushort usage_page_code, ushort usage_simple_id)
char * devid_usage_code_name_by_extended_id (uint32_t extended_usage)
Detailed Description
Lookup PCI and USB device ids
Definition in file device_id_util.h.
Function Documentation
bool devid_ensure_initialized ()
Initializes the PCI and USB id tables. If the tables are already initialized, does nothing.
Definition at line 974 of file device_id_util.c.
References bool_repr().
Referenced by adl_report_active_display(), devid_get_pci_names(), devid_get_usb_names(), devid_hid_descriptor_item_type(), devid_usage_code_id_name(), and devid_usage_code_page_name().
Pci_Usb_Id_Names devid_get_pci_names (ushort vendor_id, ushort device_id, ushort subvendor_id, ushort subdevice_id, int argct)
Gets the names associated with a PCI device.
Parameters
vendor_id
device_id
subvendor_id
subdevice_id
argct if 1, vendor_id is set if 2, vendor_id and device_id are set if 4, vendor_id, device_id, subvendor_id, and subdevice_id are set
Returns
names for the ids
Remarks
Unfortunately, both 0000 and ffff are used as ids, so these can't use them as special arguments to indicate "not set". Hence the argct parm.
Definition at line 784 of file device_id_util.c.
References Pci_Usb_Id_Names::device_name, devid_ensure_initialized(), mlm_get_names2(), Pci_Usb_Id_Names::subsys_or_interface_name, and Pci_Usb_Id_Names::vendor_name.
Referenced by adl_report_active_display().
Pci_Usb_Id_Names devid_get_usb_names (ushort vendor_id, ushort device_id, ushort interface_id, int argct)
Gets the names associated with a USB device.
Parameters
vendor_id
device_id
interface_id
argct if 1, vendor_id is set if 2, vendor_id and device_id are set if 4, vendor_id, device_id, and interface_id are set
Returns
names for the ids
Definition at line 836 of file device_id_util.c.
References Pci_Usb_Id_Names::device_name, devid_ensure_initialized(), mlm_get_names2(), Pci_Usb_Id_Names::subsys_or_interface_name, and Pci_Usb_Id_Names::vendor_name.
char* devid_hid_descriptor_item_type (ushort id)
Returns the name of USB HID descriptor item tag.
Parameters
id item tag id
Returns
name of item tag, NULL if not found
Remarks
HID documentation refers to this as item tag. usb.ids file refers to this as item type
The value is actually 1 byte.
This function corresponds to names.c function names_reporttag()
Definition at line 959 of file device_id_util.c.
References devid_ensure_initialized().
char* devid_usage_code_id_name (ushort usage_page_code, ushort usage_simple_id)
Gets the name of a HID usage code
Parameters
usage_page_code usage page
usage_simple_id id within page
Returns
usage id name, NULL if not found
Remarks
First and second fields of HUT entry in usb.ids
Corresponds to names_hutus() in names.c
Definition at line 912 of file device_id_util.c.
References devid_ensure_initialized(), and mlm_get_names().
Referenced by devid_usage_code_name_by_extended_id().
char* devid_usage_code_name_by_extended_id (uint32_t extended_usage)
Gets the name of a HID usage code, specified as a single value containing the page id in the upper 16 bits and the simple id it in the lower 16 bits.
Parameters
extended_usage usage value
Returns
usage id name, NULL if not found
Definition at line 942 of file device_id_util.c.
References devid_usage_code_id_name().
char* devid_usage_code_page_name (ushort usage_page_code)
Gets the page name for a USB usage page code
Parameters
usage_page_code
Returns
page name, NULL if invalid code
Remarks
Is top level field in HUT entry of usb.ids
Corresponds to names_huts() in names.c
Definition at line 877 of file device_id_util.c.
References devid_ensure_initialized(), and mlm_get_names().