ddcutil Internals: util/edid.h File Reference
edid.h File Reference
#include "coredefs.h"
Data Structures
struct Parsed_Edid
Functions
Byte edid_checksum (Byte *edid)
void parse_mfg_id_in_buffer (Byte *mfgIdBytes, char *buffer, int bufsize)
void get_edid_mfg_id_in_buffer (Byte *edidbytes, char *result, int bufsize)
Parsed_Edid * create_parsed_edid (Byte *edidbytes)
void report_parsed_edid_base (Parsed_Edid *edid, bool verbose, bool show_raw, int depth)
void report_parsed_edid (Parsed_Edid *edid, bool verbose, int depth)
void free_parsed_edid (Parsed_Edid *parsed_edid)
Detailed Description
Functions to interpret EDID
Definition in file edid.h.
Function Documentation
Parsed_Edid* create_parsed_edid (Byte * edidbytes)
Parses an EDID.
Parameters
edidbytes pointer to 128 byte EDID block
Returns
pointer to newly allocated Parsed_Edid struct, or NULL if the bytes could not be parsed. It is the responsiblity of the caller to free this memory.
Definition at line 214 of file edid.c.
References Parsed_Edid::bx, Parsed_Edid::by, Parsed_Edid::bytes, edid_checksum(), Parsed_Edid::edid_version_major, Parsed_Edid::edid_version_minor, Parsed_Edid::extension_flag, Parsed_Edid::extra_descriptor_string, get_edid_mfg_id_in_buffer(), Parsed_Edid::gx, Parsed_Edid::gy, hexstring(), Parsed_Edid::is_model_year, Parsed_Edid::marker, Parsed_Edid::mfg_id, Parsed_Edid::model_hex, Parsed_Edid::model_name, Parsed_Edid::rx, Parsed_Edid::ry, Parsed_Edid::serial_ascii, Parsed_Edid::serial_binary, Parsed_Edid::wx, Parsed_Edid::wy, and Parsed_Edid::year.
Referenced by adl_is_available().
Byte edid_checksum (Byte * edid)
Calculates checksum for a 128 byte EDID
Parameters
edid pointer to 128 byte EDID block
Returns
checksum byte
Note that the checksum byte (offset 127) is itself included in the checksum calculation.
Definition at line 69 of file edid.c.
Referenced by create_parsed_edid().
void free_parsed_edid (Parsed_Edid * parsed_edid)
Frees a Parsed_Edid struct.
Parameters
parsed_edid pointer to Parsed_Edid struct to free
Definition at line 300 of file edid.c.
References Parsed_Edid::marker.
void get_edid_mfg_id_in_buffer (Byte * edidbytes, char * result, int bufsize)
Extracts the 3 character manufacturer id from an EDID byte array. The id is returned with a trailing null in a buffer provided by the caller.
Parameters
edidbytes pointer to start of EDID
result buffer in which to return manufacturer ID
bufsize buffer size (must be >= 4)
Definition at line 111 of file edid.c.
References hexstring(), and parse_mfg_id_in_buffer().
Referenced by create_parsed_edid().
void parse_mfg_id_in_buffer (Byte * mfg_id_bytes, char * result, int bufsize)
Unpacks the 2 byte manufacturer id field from the EDID into a 3 character string.
Parameters
mfg_id_bytes address of first byte
result address of buffer in which to return result
bufsize buffer size; must be >= 4
Remarks
Since the unpacked value is 4 bytes in length (3 characters plus a trailing '\0') it could easily be returned on the stack. Consider.
Definition at line 89 of file edid.c.
Referenced by get_edid_mfg_id_in_buffer().
void report_parsed_edid (Parsed_Edid * edid, bool verbose, int depth)
Writes a summary of an EDID to the current report output destination. (normally stdout, but may be changed by rpt_push_output_dest())
Parameters
edid pointer to parsed edid struct
verbose include hex dump of EDID
depth logical indentation depth
Definition at line 405 of file edid.c.
References report_parsed_edid_base().
Referenced by adl_report_active_display().
void report_parsed_edid_base (Parsed_Edid * edid, bool verbose, bool show_raw, int depth)
Writes EDID summary to the current report output destination. (normally stdout, but may be changed by rpt_push_output_dest())
Parameters
edid pointer to parsed edid struct
verbose show additional detail
show_raw include hex dump of EDID
depth logical indentation depth
Remarks
Output is written using rpt_ functions.
Definition at line 320 of file edid.c.
References Parsed_Edid::bx, Parsed_Edid::by, Parsed_Edid::bytes, Parsed_Edid::edid_source, Parsed_Edid::edid_version_major, Parsed_Edid::edid_version_minor, Parsed_Edid::extension_flag, Parsed_Edid::extra_descriptor_string, Parsed_Edid::gx, Parsed_Edid::gy, Parsed_Edid::is_model_year, Parsed_Edid::mfg_id, Parsed_Edid::model_hex, Parsed_Edid::model_name, rpt_hex_dump(), rpt_vstring(), Parsed_Edid::rx, Parsed_Edid::ry, Parsed_Edid::serial_ascii, Parsed_Edid::wx, Parsed_Edid::wy, and Parsed_Edid::year.
Referenced by report_parsed_edid().