ddcutil Internals: base/execution_stats.h File Reference
execution_stats.h File Reference
#include "util/timestamp.h"
#include "base/displays.h"
#include "base/status_code_mgt.h"
Enumerations
Functions
void init_execution_stats ()
const char * io_event_name (IO_Event_Type event_type)
void log_io_call (const IO_Event_Type event_type, const char *location, long start_time_nanos, long end_time_nanos)
void report_io_call_stats (int depth)
Global_Status_Code log_status_code (Global_Status_Code rc, const char *caller_name)
void show_all_status_counts ()
bool set_sleep_strategy (int strategy)
int get_sleep_strategy ()
void call_tuned_sleep_i2c (Sleep_Event_Type event_type)
void call_tuned_sleep_adl (Sleep_Event_Type event_type)
void call_tuned_sleep_dh (Display_Handle *dh, Sleep_Event_Type event_type)
void call_tuned_sleep (DDCA_IO_Mode io_mode, Sleep_Event_Type event_type)
void report_sleep_strategy_stats (int depth)
Detailed Description
Record execution statistics, namely the count and elapsed time of system calls.
Definition in file execution_stats.h.
Enumeration Type Documentation
enum IO_Event_Type
IO Event type. Statistics for each event type are recorded separately.
Definition at line 53 of file execution_stats.h.
Function Documentation
void call_tuned_sleep (DDCA_IO_Mode io_mode, Sleep_Event_Type event_type)
Sleep for a period required by the DDC protocol.
This function allows for tuning the actual sleep time.
This function does 3 things:
Determine the sleep period based on the communication mechanism, call type, sleep strategy in effect, and potentially other information.
Record the sleep event.
Sleep for period determined.
Parameters
io_mode communication mechanism
event_type reason for sleep
Todo:
Extend to take account of actual time since return from last system call, previous error rate, etc.
Definition at line 483 of file execution_stats.c.
References DDC_IO_ADL, DDC_IO_DEVI2C, and USB_IO.
Referenced by call_tuned_sleep_adl(), call_tuned_sleep_dh(), and call_tuned_sleep_i2c().
void call_tuned_sleep_adl (Sleep_Event_Type event_type)
Convenience function that invokes call_tuned_sleep() for ADL devices.
Parameters
event_type sleep event type
Definition at line 577 of file execution_stats.c.
References call_tuned_sleep(), and DDC_IO_ADL.
void call_tuned_sleep_dh (Display_Handle * dh, Sleep_Event_Type event_type)
Convenience function that determines the device type from the Display_Handle before invoking all_tuned_sleep().
Parameters
dh display handle of open device
event_type sleep event type
Definition at line 586 of file execution_stats.c.
References call_tuned_sleep().
void call_tuned_sleep_i2c (Sleep_Event_Type event_type)
Convenience function that invokes call_tuned_sleep() for /dev/i2c devices.
Parameters
event_type sleep event type
Definition at line 567 of file execution_stats.c.
References call_tuned_sleep(), and DDC_IO_DEVI2C.
int get_sleep_strategy ()
Gets the current sleep strategy number
Definition at line 440 of file execution_stats.c.
void init_execution_stats ()
Initialize execution stats module
Definition at line 617 of file execution_stats.c.
References cur_realtime_nanosec().
Referenced by init_base_services().
const char* io_event_name (IO_Event_Type event_type)
Returns type symbolic name of an even type.
Parameters
event_type
Returns
symbolic name
Definition at line 107 of file execution_stats.c.
Referenced by log_io_call().
void log_io_call (const IO_Event_Type event_type, const char * location, long start_time_nanos, long end_time_nanos)
Called immediately after an I2C IO call, this function updates two sets of data:
1) Updates the total number of calls and elapsed time for categories of calls.
2) Updates the timestamp and call type maintained for the most recent I2C call. This information is used to determine the required time for the next sleep call.
Parameters
event_type e.g. IE_WRITE
location function name
start_time_nanos starting time of the event in nanoseconds
end_time_nanos ending time of the event in nanoseconds
Definition at line 164 of file execution_stats.c.
References io_event_name().
Global_Status_Code log_status_code (int rc, const char * caller_name)
Log a status code occurrence
Parameters
rc status code
caller_name function logging the event
Definition at line 273 of file execution_stats.c.
References ddcrc_is_derived_status_code(), ddcrc_is_not_error(), find_global_status_code_info(), and g_list_to_g_array().
void report_io_call_stats (int depth)
Reports the accumulated execution statistics
Parameters
depth logical indentation depth
Definition at line 187 of file execution_stats.c.
References rpt_vstring().
void report_sleep_strategy_stats (int depth)
Reports sleep strategy statistics.
Parameters
depth logical indentation depth
Definition at line 597 of file execution_stats.c.
References rpt_nl(), and rpt_vstring().
bool set_sleep_strategy (int strategy)
Rudimentary mechanism for changing the sleep strategy.
Definition at line 427 of file execution_stats.c.
void show_all_status_counts ()
Master function to display status counts
Definition at line 365 of file execution_stats.c.
References g_list_to_g_array().