ddcutil Internals: util/failsim.h File Reference
failsim.h File Reference
#include "config.h"
Enumerations
Functions
void fsim_set_name_to_number_funcs (Fsim_Name_To_Number_Func func, Fsim_Name_To_Number_Func unmodulated_func)
void fsim_add_error (char *funcname, Fsim_Call_Occ_Type call_occ_type, int occno, int rc)
void fsim_clear_errors_for_func (char *funcname)
void fsim_report_error_table (int depth)
void fsim_reset_callct (char *funcname)
bool fsim_load_control_from_gptrarray (GPtrArray *lines)
bool fsim_load_control_file (char *fn)
Failsim_Result fsim_check_failure (const char *fn, const char *funcname)
Detailed Description
Functions that provide a simple failure simulation framework.
Definition in file failsim.h.
Enumeration Type Documentation
enum Fsim_Call_Occ_Type
Indicates whether a failure should occur exactly one or be recurring
Definition at line 54 of file failsim.h.
Function Documentation
void fsim_add_error (char * funcname, Fsim_Call_Occ_Type call_occ_type, int occno, int rc)
Adds an error description to the failure simulation table entry for a function.
Parameters
funcname function name
call_occ_type recurring or single
occno occurrence number
rc return code to simulate
Definition at line 191 of file failsim.c.
Referenced by fsim_load_control_from_gptrarray().
Failsim_Result fsim_check_failure (const char * fn, const char * funcname)
This function is called at runtime to check if a failure should be simulated.
Parameters
fn name of file from which check is performed
funcname name of function for which check is performed
Returns
struct indicating whether failure should be simulated and if so what the status code should be. Note that the entire struct is returned on the stack, not a pointer to the struct.
Definition at line 492 of file failsim.c.
References show_backtrace().
void fsim_clear_errors_for_func (char * funcname)
Delete all error descriptors for a function.
Parameters
funcname function name
Definition at line 234 of file failsim.c.
bool fsim_load_control_file (char * fn)
Loads the failure simulation table from a control file.
Parameters
fn file name
Returns
true if success, fails if error
Definition at line 457 of file failsim.c.
References bool_repr(), file_getlines(), and fsim_load_control_from_gptrarray().
bool fsim_load_control_from_gptrarray (GPtrArray * lines)
Load the failure simulation table from an array of strings. Each string describes one simulated error for a function, and has the form:
  function_name  status_code occurrence_descriptor
where:
status_code has a form documented for eval_fsim_rc()
occurrence_descriptor has the form "[*]integer"
examples:
*7 every 7th call fails
7 the 7th call fails
*1 every call fails
Examples:
  i2c_set_addr  base:EBUSY 6
  ddc_verify    false      *1
Parameters
lines array of lines
Definition at line 366 of file failsim.c.
References bool_repr(), fsim_add_error(), ntsa_free(), ntsa_length(), strsplit(), and strtrim().
Referenced by fsim_load_control_file().
void fsim_report_error_table (int depth)
Report the failure simulation table.
Parameters
depth logical indentation depth
Definition at line 256 of file failsim.c.
References bool_repr(), rpt_vstring(), str_starts_with(), and streq().
void fsim_reset_callct (char * funcname)
Resets the call counter in a failure simulation table entry
Parameters
funcname function name
Definition at line 221 of file failsim.c.
void fsim_set_name_to_number_funcs (Fsim_Name_To_Number_Func func, Fsim_Name_To_Number_Func unmodulated_func)
Sets the functions to bu used to interpret a symbolic value in a control file.
Definition at line 50 of file failsim.c.
References rpt_vstring().