ddcutil Internals: Abnormal Termination
Abnormal Termination
Macros
#define PROGRAM_LOGIC_ERROR(format, ...) program_logic_error(__func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
#define TERMINATE_EXECUTION_ON_ERROR(format, ...) terminate_execution_on_error(TRACE_GROUP, __func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
Functions
void register_jmp_buf (jmp_buf *jb)
void ddc_abort (const char *funcname, const int lineno, const char *fn, int status)
Detailed Description
Macro Definition Documentation
#define PROGRAM_LOGIC_ERROR (format, ...) program_logic_error(__func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
Wraps call to program_logic_error()
Reports an error in program logic and terminates execution.
Definition at line 288 of file core.h.
#define TERMINATE_EXECUTION_ON_ERROR (format, ...) terminate_execution_on_error(TRACE_GROUP, __func__, __LINE__, __FILE__, format, ##__VA_ARGS__)
Wraps call to terminate_execution_on_error()
Definition at line 304 of file core.h.
Function Documentation
void ddc_abort (const char * funcname, const int lineno, const char * fn, int status)
Primary function for terminating ddcutil execution due to an internal error.
If a longjump jump buffer has been registered, basic error information is stored in buffer global_failure_information, and longjmp() is called. Otherwise, exit() is called.
Parameters
funcname function name of error
lineno line number of error
fn file name of error
status status code
Definition at line 227 of file core.c.
References CALLOPT_ERR_ABORT, CALLOPT_ERR_MSG, CALLOPT_FORCE, CALLOPT_NONE, CALLOPT_RDONLY, CALLOPT_WARN_FINDEX, f0puts(), FERR, show_backtrace(), VN, VN_END, and vnt_interpret_flags().
Referenced by is_tracing(), program_logic_error(), and terminate_execution_on_error().
void register_jmp_buf (jmp_buf * jb)
Registers the longjmp() target with the ddcutil library.
Parameters
jb pointer to jmp_buf
Definition at line 206 of file core.c.