ddcutil Internals: Basic Output Redirection
Basic Output Redirection
Functions
void init_msg_control ()
void set_fout (FILE *fout)
void set_fout_to_default ()
void set_ferr (FILE *ferr)
void set_ferr_to_default ()
void program_logic_error (const char *funcname, const int lineno, const char *fn, char *format,...)
void terminate_execution_on_error (Trace_Group trace_group, const char *funcname, const int lineno, const char *fn, char *format,...)
Variables
FILE * FOUT = NULL
FILE * FERR = NULL
Detailed Description
Function Documentation
void init_msg_control ()
Initialize stdout and stderr redirection.
Must be called during program initialization.
Definition at line 108 of file core.c.
References FERR, and FOUT.
Referenced by init_base_services().
void program_logic_error (const char * funcname, const int lineno, const char * fn, char * format, ...)
Called when a condition that should be impossible has been detected. Issues messages to stderr and terminates execution.
This function is normally invoked using macro PROGRAM_LOGIC_ERROR()
Parameters
funcname function name
lineno line number in source file
fn source file name
format format string, as in printf()
... one or more substitution values for the format string
Definition at line 954 of file core.c.
References ddc_abort(), f0puts(), and FERR.
void set_ferr (FILE * ferr)
Redirect output that would normally go to stderr..
Parameters
ferr pointer to output stream
Definition at line 145 of file core.c.
References FERR.
void set_ferr_to_default ()
Redirect output that would normally go to stderr back to stderr.
Definition at line 152 of file core.c.
References FERR.
void set_fout (FILE * fout)
Redirect output that would normally go to stdout.
Parameters
fout pointer to output stream
Definition at line 125 of file core.c.
References FOUT, and rpt_change_output_dest().
void set_fout_to_default ()
Redirect output that would normally go to stdout back to stdout.
Definition at line 135 of file core.c.
References FOUT, and rpt_change_output_dest().
void terminate_execution_on_error (Trace_Group trace_group, const char * funcname, const int lineno, const char * fn, char * format, ...)
This function is called to terminate execution on a fatal error.
It is normally wrapped in macro TERMINATE_EXECUTION_ON_ERROR(format,...)
Parameters
trace_group trace group for function where error occurred
funcname function name
lineno line number
fn file name
format printf() style format string
... arguments for format string
Definition at line 996 of file core.c.
References ddc_abort(), f0puts(), FERR, and is_tracing().
Variable Documentation
FILE* FERR = NULL
Current stream for error messages.
Remarks
Will be NULL until init_msg_control() is called. Be careful during program initialization.
Definition at line 86 of file core.c.
Referenced by adl_get_display_by_adlno(), ddc_abort(), init_msg_control(), is_tracing(), program_logic_error(), set_ferr(), set_ferr_to_default(), and terminate_execution_on_error().
FILE* FOUT = NULL
Current stream for normal output.
Remarks
Will be NULL until init_msg_control() is called. Be careful during program initialization.
Definition at line 76 of file core.c.
Referenced by init_msg_control(), interpret_call_options(), is_tracing(), set_fout(), and set_fout_to_default().