ddcutil Internals: Message Level Management
Message Level Management
Functions
DDCA_Output_Level get_output_level ()
void set_output_level (DDCA_Output_Level newval)
char * output_level_name (DDCA_Output_Level val)
void show_output_level ()
Detailed Description
Functions and variables to manage and query output level settings.
Function Documentation
DDCA_Output_Level get_output_level ()
Gets the current output level.
Returns
output level
Definition at line 423 of file core.c.
Referenced by adl_report_active_display().
char* output_level_name (DDCA_Output_Level val)
Gets the printable name of an output level.
Parameters
val output level
Returns
printable name for output level
Definition at line 445 of file core.c.
References OL_NORMAL, OL_TERSE, and OL_VERBOSE.
Referenced by show_output_level().
void set_output_level (DDCA_Output_Level newval)
Sets the output level.
Parameters
newval output level to set
Definition at line 433 of file core.c.
void show_output_level ()
Reports the current output level to the current FOUT device.
Definition at line 478 of file core.c.
References ARRAY_SIZE, output_level_name(), VNT, and VNT_END.
Referenced by is_tracing().