ddcutil Internals: util/libdrm_util.h File Reference
libdrm_util.h File Reference
Functions
char * connector_type_name (Byte val)
char * connector_type_title (Byte val)
char * connector_status_name (drmModeConnection val)
char * connector_status_title (drmModeConnection val)
char * encoder_type_title (uint32_t encoder_type)
void report_drmModeRes (drmModeResPtr res, int depth)
void report_drmModePropertyBlob (drmModePropertyBlobPtr blob_ptr, int depth)
void report_drm_modeProperty (drmModePropertyRes *p, int depth)
void summarize_drm_modeProperty (drmModePropertyRes *p, int depth)
Detailed Description
Utilities for use with libdrm
Definition in file libdrm_util.h.
Function Documentation
char* connector_status_name (drmModeConnection val)
Returns the symbolic name of a drmModeConnection value.
Parameters
val connection state
Returns
symbolic name
Definition at line 216 of file libdrm_util.c.
References vnt_name().
Referenced by report_drmModeRes().
char* connector_status_title (drmModeConnection val)
Returns a description string for a drmModeConnection value.
Parameters
val connection state
Returns
descriptive string
Definition at line 225 of file libdrm_util.c.
References VNT, VNT_END, and vnt_title().
char* connector_type_name (Byte val)
Returns the symbolic name of a connector type.
Parameters
val connector type
Returns
symbolic name
Definition at line 82 of file libdrm_util.c.
References vnt_name().
Referenced by report_drmModeRes().
char* connector_type_title (Byte val)
Returns the description string for a connector type.
Parameters
val connector type
Returns
descriptive string
Definition at line 91 of file libdrm_util.c.
References sbuf_append(), VN, VN_END, VNT, VNT_END, vnt_interpret_flags(), and vnt_title().
char* encoder_type_title (uint32_t encoder_type)
Returns a description string for an encoder type
Parameters
encoder_type encolder type
Returns
descriptive string
Definition at line 246 of file libdrm_util.c.
References sbuf_append(), and vnt_title().
void report_drm_modeProperty (drmModePropertyRes * p, int depth)
Reports a **drmModePropertyRes struct
Parameters
p pointer to drmModePropertyRes
depth logical indentation deptn
Definition at line 642 of file libdrm_util.c.
References rpt_structure_loc(), and rpt_vstring().
void report_drmModePropertyBlob (drmModePropertyBlobPtr blob_ptr, int depth)
Reports the raw bytes of a blob.
Parameters
blob_ptr pointer to a drmModePropertyBlobRes
depth logical indentation depth
Definition at line 525 of file libdrm_util.c.
References rpt_hex_dump(), and rpt_vstring().
Referenced by report_property_value().
void report_drmModeRes (drmModeResPtr res, int depth)
Reports a drmModeRes struct.
Parameters
res pointer to drmModeRes instance
depth logical indentation depth
Definition at line 297 of file libdrm_util.c.
References connector_status_name(), connector_type_name(), report_property_value(), rpt_nl(), rpt_structure_loc(), and rpt_vstring().
void summarize_drm_modeProperty (drmModePropertyRes * p, int depth)
Emits a summary report for a **drmModePropertyRes struct
Parameters
p pointer to drmModePropertyRes
depth logical indentation deptn
Definition at line 669 of file libdrm_util.c.
References rpt_vstring().