ddcutil Internals: base/linux_errno.h File Reference
linux_errno.h File Reference
#include "base/status_code_mgt.h"
Functions
void init_linux_errno ()
bool errno_name_to_number (const char *errno_name, int *perrno)
bool errno_name_to_modulated_number (const char *errno_name, Global_Status_Code *p_error_number)
Detailed Description
Linux errno descriptions
Definition in file linux_errno.h.
Function Documentation
bool errno_name_to_modulated_number (const char * errno_name, Global_Status_Code * p_error_number)
Gets the Linux error number for a symbolic name. The value is returned as a negative, modulated number.
Parameters
errno_name symbolic name, e.g. EBUSY
p_error_number where to return error number
Returns
true if found, false if not
Definition at line 306 of file linux_errno.c.
References errno_name_to_number(), modulate_rc(), and RR_ERRNO.
bool errno_name_to_number (const char * errno_name, int * perrno)
Gets the Linux error number for a symbolic name. The value is returned as a negative number.
Parameters
errno_name symbolic name, e.g. EBUSY
perrno where to return error number
Returns
true if found, false if not
Definition at line 285 of file linux_errno.c.
References streq().
Referenced by errno_name_to_modulated_number().
void init_linux_errno ()
Initialize linux_errno.c
Definition at line 51 of file linux_errno.c.
References RR_ERRNO.