ddcutil Internals: util/multi_level_map.h File Reference
multi_level_map.h File Reference
Functions
void report_mlm_level (MLM_Level *level_desc, int depth)
Multi_Level_Map * mlm_create (char *table_name, int levels, MLM_Level *level_detail)
MLM_Node * mlm_add_node (Multi_Level_Map *mlm, MLM_Node *parent, uint key, char *value)
void report_multi_level_map (Multi_Level_Map *mlm, int depth)
Multi_Level_Names mlm_get_names (Multi_Level_Map *mlm, int argct,...)
Multi_Level_Names mlm_get_names2 (Multi_Level_Map *mlm, int levelct, uint *ids)
Detailed Description
Multi_Level_Map data structure
Definition in file multi_level_map.h.
Function Documentation
MLM_Node* mlm_add_node (Multi_Level_Map * map, MLM_Node * parent, uint key, char * value)
Adds a node to a Multi_Level_Map.
Parameters
map pointer to Multi_Level_Map table
parent pointer to parent node if NULL, this node is a child of the root
key key of node
value value of node
Definition at line 80 of file multi_level_map.c.
Multi_Level_Map* mlm_create (char * table_name, int levels, MLM_Level * level_detail)
Creates a new **Multi_Level_Map instance.
Parameters
table_name name of table
levels number of levels
level_detail pointer to array if MLM_Level descriptors
Definition at line 54 of file multi_level_map.c.
Multi_Level_Names mlm_get_names (Multi_Level_Map * table, int argct, ...)
Variant of mlm_get_names2() that uses a variable argument list for the level ids.
Parameters
table pointer to Multi_Level_Map table
argct number of ids
.. node ids, of type uint
Returns
pointer to Multi_Level_Names struct containing the names for the ids at each level
Definition at line 272 of file multi_level_map.c.
References mlm_get_names2().
Referenced by devid_usage_code_id_name(), and devid_usage_code_page_name().
Multi_Level_Names mlm_get_names2 (Multi_Level_Map * mlm, int levelct, uint * ids)
Gets the names associated with the levels of a Multi_Level_Map path.
Parameters
mlm pointer to Multi_Level_Map table
levelct number of ids
ids pointer to array of levelct node ids
Returns
pointer to Multi_Level_Names struct containing the names for the ids at each level
Definition at line 224 of file multi_level_map.c.
Referenced by devid_get_pci_names(), devid_get_usb_names(), and mlm_get_names().
void report_mlm_level (MLM_Level * level_desc, int depth)
Reports on a Multi_Level_Map level descriptor.
Parameters
level_desc pointer to level descriptor
depth logical indentation depth
Definition at line 112 of file multi_level_map.c.
References rpt_int(), rpt_str(), rpt_structure_loc(), and rpt_vstring().
void report_multi_level_map (Multi_Level_Map * header, int depth)
Reports the contents of a Multi_Level_Map.
Parameters
header pointer to MLM instance
depth logical indentation depth
Definition at line 158 of file multi_level_map.c.
References rpt_int(), rpt_str(), rpt_structure_loc(), and rpt_vstring().