ddcutil Internals: util/report_util.h File Reference
report_util.h File Reference
#include "coredefs.h"
Typedefs
typedef char *(* Value_To_Name_Function) (int val)
Functions
void rpt_push_output_dest (FILE *new_dest)
void rpt_pop_output_dest ()
FILE * rpt_cur_output_dest ()
void rpt_reset_output_dest_stack ()
void rpt_change_output_dest (FILE *new_dest)
void rpt_debug_output_dest ()
int rpt_get_indent (int depth)
void rpt_nl ()
void rpt_multiline (int depth,...)
void rpt_g_ptr_array (int depth, GPtrArray *strings)
void rpt_vstring (int depth, char *format,...)
void rpt_2col (char *s1, char *s2, int col2offset, bool offset_absolute, int depth)
void rpt_structure_loc (const char *name, const void *ptr, int depth)
void rpt_hex_dump (const Byte *data, int size, int depth)
void rpt_str (const char *name, char *info, const char *val, int depth)
void rpt_int (char *name, char *info, int val, int depth)
void rpt_bool (char *name, char *info, bool val, int depth)
void rpt_mapped_int (char *name, char *info, int val, Value_To_Name_Function func, int depth)
void rpt_int_as_hex (char *name, char *info, int val, int depth)
void rpt_uint8_as_hex (char *name, char *info, unsigned char val, int depth)
void rpt_bytes_as_hex (const char *name, char *info, Byte *bytes, int ct, bool hex_prefix_flag, int depth)
void rpt_ifval2 (char *name, char *info, int val, Flag_Name_Set *pflagNameSet, Flag_Dictionary *pDict, int depth)
Detailed Description
Report utility package
Definition in file report_util.h.
Typedef Documentation
typedef char*(* Value_To_Name_Function) (int val)
Interpretation function used by rpt_mapped_int()
Definition at line 67 of file report_util.h.
Function Documentation
void rpt_2col (char * s1, char * s2, int col2offset, bool offset_absolute, int depth)
Writes a pair of strings to the current output destination.
If offset_absolute is true, then the s2 value will start in the same column, irrespective of the line indentation. This may make some reports easier to read.
Parameters
s1 first string
s2 second string
col2offset offset from start of line where s2 starts
offset_absolute if true, col2offset is relative to the start of the line, before indentation if false, col2offset is relative to the indented start of s1
depth logical indentation depth
Definition at line 315 of file report_util.c.
References file_getlines(), rpt_get_indent(), rpt_vstring(), and rtrim_in_place().
void rpt_bool (char * name, char * info, bool val, int depth)
Writes a string to the current output destination describing a boolean value.
The value is displayed as "true" or "false".
The output is indented per the specified indentation depth. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val value to show
depth logical indentation depth
The value is formatted as "true" or "false".
Definition at line 398 of file report_util.c.
References rpt_str().
void rpt_bytes_as_hex (const char * name, char * info, Byte * bytes, int ct, bool hex_prefix_flag, int depth)
Writes a string to the current output destination describing a sequence of bytes, indented per the specified indentation depth.
The value is formatted as printable hex.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
bytes pointer to start of bytes to show
ct number of bytes to show
hex_prefix_flag if true, the printable hex value will begin with "0x"
depth logical indentation depth
Definition at line 512 of file report_util.c.
References hexstring(), rpt_int(), rpt_int_as_hex(), rpt_str(), rpt_structure_loc(), and streq().
void rpt_change_output_dest (FILE * new_dest)
Changes the current output destination, without saving the current output destination on the destination stack.
Parameters
new_dest new output destination
Remarks
Needed for set_fout() in core.c
Definition at line 172 of file report_util.c.
References rpt_cur_output_dest().
Referenced by set_fout(), and set_fout_to_default().
FILE* rpt_cur_output_dest ()
Gets the current output destination.
Returns
current output destination
Definition at line 144 of file report_util.c.
Referenced by rpt_change_output_dest(), rpt_debug_output_dest(), rpt_hex_dump(), rpt_nl(), and rpt_str().
void rpt_debug_output_dest ()
Debugging function to show output destination.
Definition at line 158 of file report_util.c.
References rpt_cur_output_dest().
void rpt_g_ptr_array (int depth, GPtrArray * strings)
Writes all strings in a GPtrArray to the current report destination
Parameters
depth logical indentation depth
strings pointer to GPtrArray of strings
Definition at line 269 of file report_util.c.
int rpt_get_indent (int depth)
Given a logical indentation depth, returns the number of spaces of indentation to be used.
Parameters
depth logical indentation depth
Returns
number of indentation spaces
Definition at line 102 of file report_util.c.
Referenced by rpt_2col(), rpt_hex_dump(), and rpt_nl().
void rpt_hex_dump (const Byte * data, int size, int depth)
Writes a hex dump with indentation. Output is written to the current report destination
Parameters
data start of bytes to dump
size number of bytes to dump
depth logical indentation depth
Definition at line 284 of file report_util.c.
References fhex_dump_indented(), rpt_cur_output_dest(), and rpt_get_indent().
Referenced by report_drmModePropertyBlob(), and report_parsed_edid_base().
void rpt_ifval2 (char * name, char * info, int val, Flag_Name_Set * p_flag_name_set, Flag_Dictionary * p_dict, int depth)
Writes a string to the current output destination describing an integer that is to be interpreted as a named collection of named bits.
Output is indented per the specified indentation depth. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val value to interpret
p_flag_name_set
p_dict
depth logical indentation depth
Definition at line 641 of file report_util.c.
References rpt_str().
void rpt_int (char * name, char * info, int val, int depth)
Writes a string to the current output destination, describing a named integer value.
The output is indented per the specified indentation depth.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val integer value
depth logical indentation depth
Definition at line 418 of file report_util.c.
References rpt_str().
Referenced by adl_get_valid_displays(), report_mlm_level(), report_multi_level_map(), and rpt_bytes_as_hex().
void rpt_int_as_hex (char * name, char * info, int val, int depth)
Writes a string to the current output destination describing a 4 byte integer value, indented per the specified indentation depth.
The integer value is formatted as printable hex.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val integer value
depth logical indentation depth
Definition at line 440 of file report_util.c.
References rpt_str().
Referenced by rpt_bytes_as_hex().
void rpt_mapped_int (char * name, char * info, int val, Value_To_Name_Function func, int depth)
Writes a string to the current output destination describing a named integer value having a symbolic string representation.
The output is indented per the specified indentation depth.
The integer value is converted to a string using the specified function.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val integer value
func interpretation function
depth logical indentation depth
Definition at line 487 of file report_util.c.
References rpt_str().
void rpt_multiline (int depth, ...)
Convenience function that writes multiple constant strings.
Parameters
depth logical indentation depth
... pointers to constant strings, last pointer is NULL to terminate list
Definition at line 253 of file report_util.c.
void rpt_nl ()
Writes a newline to the current output destination.
Definition at line 190 of file report_util.c.
References f0printf(), rpt_cur_output_dest(), and rpt_get_indent().
Referenced by report_drmModeRes(), and report_sleep_strategy_stats().
void rpt_pop_output_dest ()
Pops the output destination stack, and sets the output destination to be used for report functions to the new top of the stack.
Definition at line 126 of file report_util.c.
void rpt_push_output_dest (FILE * new_dest)
Sets the output destination to be used for report functions. The current output destination is saved on the output destination stack.
Parameters
new_dest new output destination
Definition at line 117 of file report_util.c.
void rpt_reset_output_dest_stack ()
Clears the output destination stack. The output destination to be used for report functions to the default (stdout).
Definition at line 135 of file report_util.c.
void rpt_str (const char * name, char * info, const char * val, int depth)
Writes a string to the current output destination describing a named character string value.
The output is indented per the specified indentation depth.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The string value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val string value
depth logical indentation depth
Definition at line 368 of file report_util.c.
References rpt_cur_output_dest(), and rpt_vstring().
Referenced by adl_get_valid_displays(), report_mlm_level(), report_multi_level_map(), report_usb_detailed_device_summary(), rpt_bool(), rpt_bytes_as_hex(), rpt_ifval2(), rpt_int(), rpt_int_as_hex(), rpt_mapped_int(), and rpt_uint8_as_hex().
void rpt_structure_loc (const char * name, const void * ptr, int depth)
Writes a string to the current output destination, describing a pointer to a named data structure.
The output is indented per the specified indentation depth.
Parameters
name struct name
ptr pointer to struc
depth logical indentation depth
Definition at line 298 of file report_util.c.
References rpt_vstring().
Referenced by adl_get_valid_displays(), report_drm_modeProperty(), report_drmModeRes(), report_mlm_level(), report_multi_level_map(), report_udev_device(), report_udev_usb_devinfo(), report_usb_detailed_device_summary(), and rpt_bytes_as_hex().
void rpt_uint8_as_hex (char * name, char * info, unsigned char val, int depth)
Writes a string to the current output destination describing a single byte value, indented per the specified indentation depth.
The value is formatted as printable hex.
Optionally, a description string can be specified along with the name. The description string will be surrounded by parentheses.
The value is prefixed with a colon.
Parameters
name name of value
info if non-null, description of value
val value
depth logical indentation depth
Definition at line 462 of file report_util.c.
References rpt_str().
void rpt_vstring (int depth, char * format, ...)
Writes a formatted string to the current output destination.
A newline is appended to the string specified
Parameters
depth logical indentation depth
format format string (normal printf)
... arguments
Remarks
Note that the depth parm is first on this function because of variable args
Definition at line 224 of file report_util.c.
Referenced by adl_report_active_display(), adl_report_active_display_by_index(), adl_report_active_displays(), fsim_report_error_table(), fsim_set_name_to_number_funcs(), lookup_udev_usb_device_by_devname(), probe_udev_subsystem(), report_drm_modeProperty(), report_drmModePropertyBlob(), report_drmModeRes(), report_io_call_stats(), report_mlm_level(), report_multi_level_map(), report_parsed_edid_base(), report_property_value(), report_sleep_strategy_stats(), report_udev_device(), report_udev_usb_devinfo(), rpt_2col(), rpt_str(), rpt_structure_loc(), and summarize_drm_modeProperty().