ddcutil Internals: base/status_code_mgt.h File Reference
status_code_mgt.h File Reference
Data Structures
struct Status_Code_Info
Typedefs
typedef int Global_Status_Code
typedef Status_Code_Info *(* Retcode_Description_Finder) (int rc)
Enumerations
Functions
void init_status_code_mgt ()
void report_status_code_info (Status_Code_Info *pdesc)
int modulate_rc (int unmodulated_rc, Retcode_Range_Id range_id)
int demodulate_rc (int modulated_rc, Retcode_Range_Id range_id)
Retcode_Range_Id get_modulation (int rc)
Status_Code_Info * find_global_status_code_info (Global_Status_Code rc)
char * gsc_desc (Global_Status_Code rc)
char * gsc_name (Global_Status_Code status_code)
bool gsc_name_to_unmodulated_number (const char *status_code_name, int *p_error_number)
bool gsc_name_to_modulated_number (const char *status_code_name, Global_Status_Code *p_error_number)
Detailed Description
Status Code Management
Definition in file status_code_mgt.h.
Typedef Documentation
typedef int Global_Status_Code
Fully modulated status code
Definition at line 63 of file status_code_mgt.h.
typedef Status_Code_Info*(* Retcode_Description_Finder) (int rc)
typedef of function used to return a Status_Code_Info for a status code
Definition at line 83 of file status_code_mgt.h.
Enumeration Type Documentation
enum Retcode_Range_Id
Status code range identifiers
Remarks
must be kept consistent with table in status_code_mgt.c
should RR_BASE be in this enum?
Enumerator
RR_BASE
indicates unmodulated status code
RR_ERRNO
range id for modulated Linux errno values
RR_ADL
range id for modulated ADL error codes
RR_DDC
range id for modulated ddcutil-specific error codes
Definition at line 110 of file status_code_mgt.h.
Function Documentation
int demodulate_rc (int rc, Retcode_Range_Id range_id)
Shifts a status code from the specified modulation range to the base range
Parameters
rc status code to demodulate
range_id a modulation range
Returns
demodulated status code
Remarks
It is an error to pass an unmodulated status code as an argument to this funtion.
Definition at line 214 of file status_code_mgt.c.
Referenced by find_global_status_code_info(), and get_modulation().
Status_Code_Info* find_global_status_code_info (Global_Status_Code gsc)
Given a Global_Status_Code, returns a pointer to its Status_Code_Info struct.
Parameters
gsc global (modulated) status code
Returns
pointer to Status_Code_Info for staus code, NULL if not found
Definition at line 284 of file status_code_mgt.c.
References demodulate_rc(), get_modulation(), and report_status_code_info().
Referenced by gsc_desc(), gsc_name(), and log_status_code().
Retcode_Range_Id get_modulation (int rc)
Determines the modulation range for a status code. Can be either the base range or a modulation range
Parameters
rc status code to check
Returns
range identifier
Definition at line 234 of file status_code_mgt.c.
References demodulate_rc(), get_modulation(), modulate_rc(), RR_BASE, and RR_ERRNO.
Referenced by find_global_status_code_info(), and get_modulation().
char* gsc_desc (Global_Status_Code status_code)
Returns a description string for a Global_Status_Code. Synthesizes a description if information for the status code cannot be found.
Parameters
status_code global (modulated) status code
Returns
string description of status code
Remarks
The value returned is valid unti the next call of this function.
Definition at line 329 of file status_code_mgt.c.
References find_global_status_code_info().
char* gsc_name (Global_Status_Code status_code)
Returns the symbolic name of a Global_Status_Code
Parameters
status_code global (modulated) status code
Returns
symbolic name, or "" if not found
Definition at line 351 of file status_code_mgt.c.
References find_global_status_code_info().
bool gsc_name_to_modulated_number (const char * status_code_name, Global_Status_Code * p_error_number)
Given a status code name, convert it to a modulated Global_Status_Code.
Parameters
status_code_name
p_error_number where to return status code number
Returns
true if conversion successful, false if unrecognized status code
Definition at line 390 of file status_code_mgt.c.
bool gsc_name_to_unmodulated_number (const char * status_code_name, int * p_error_number)
Given a status code name, convert it to a unmodulated base status code Valid only for those status code ranges which ...
Parameters
status_code_name
p_error_number where to return status code number
Returns
true if conversion successful, false if unrecognized status code
Definition at line 366 of file status_code_mgt.c.
void init_status_code_mgt ()
Initialize this module.
Definition at line 416 of file status_code_mgt.c.
Referenced by init_base_services().
int modulate_rc (int rc, Retcode_Range_Id range_id)
Shifts a status code in the RR_BASE range to a specified range.
Parameters
rc base status code to modulate
range_id range to which status code should be modulated
Returns
modulated status code
Remarks
It is an error to pass an already modulated status code as an argument to this function.
Definition at line 185 of file status_code_mgt.c.
Referenced by adl_error_name_to_modulated_number(), adlshim_ddc_read_only(), adlshim_ddc_write_only(), adlshim_get_video_card_info(), errno_name_to_modulated_number(), and get_modulation().
void report_status_code_info (Status_Code_Info * pdesc)
Display the contents of a Status_Code_Info struct. This is a debugging function.
Parameters
pdesc pointer to Status_Code_Info struct
Definition at line 431 of file status_code_mgt.c.
Referenced by find_global_status_code_info().