ddcutil Internals: util/string_util.h File Reference
string_util.h File Reference
#include "coredefs.h"
#include "glib_util.h"
Functions
char * bool_repr (int value)
bool streq (const char *s1, const char *s2)
bool is_abbrev (const char *value, const char *longname, int minchars)
bool str_starts_with (const char *value_to_test, const char *start_part)
bool str_ends_with (const char *value_to_test, const char *end_part)
bool str_all_printable (const char *s)
char * strupper (char *s)
char * strdup_uc (const char *s)
char * strjoin (const char **pieces, const int ct, const char *sepstr)
char * chars_to_string (const char *start, int len)
char * strtrim (const char *s)
char * strtrim_r (const char *s, char *buffer, int bufsz)
char * rtrim_in_place (char *s)
char * substr (const char *s, int startpos, int ct)
char * lsub (const char *s, int ct)
char * strcat_new (char *s1, char *s2)
bool sbuf_append (char *buf, int bufsz, char *sepstr, char *nextval)
int matches_by_func (const char *word, char **match_list, String_Comp_Func comp_func)
int exactly_matches_any (const char *word, char **match_list)
int starts_with_any (const char *word, char **match_list)
void ntsa_free (Null_Terminated_String_Array string_array)
int ntsa_length (Null_Terminated_String_Array string_array)
Null_Terminated_String_Array strsplit (const char *str_to_split, const char *delims)
Null_Terminated_String_Array strsplit_maxlength (const char *str_to_split, uint16_t max_piece_length, const char *delims)
GPtrArray * ntsa_to_g_ptr_array (Null_Terminated_String_Array ntsa)
Null_Terminated_String_Array g_ptr_array_to_ntsa (GPtrArray *garray)
bool str_to_int (const char *nptr, int *ival)
bool hhs_to_byte_in_buf (const char *s, Byte *result)
bool any_one_byte_hex_string_to_byte_in_buf (const char *s, Byte *result)
bool hhc_to_byte_in_buf (const char *hh, Byte *result)
int hhs_to_byte_array (const char *hhs, Byte **pBa)
char * hexstring (const Byte *bytes, int size)
char * hexstring2 (const unsigned char *bytes, int len, const char *sepstr, bool uppercase, char *buffer, int bufsz)
void fhex_dump_indented (FILE *fh, const Byte *data, int size, int indents)
void fhex_dump (FILE *fh, const Byte *bytes, int size)
void hex_dump (const Byte *bytes, int size)
int f0putc (int c, FILE *stream)
int f0puts (const char *s, FILE *stream)
int f0printf (FILE *stream, const char *format,...)
int vf0printf (FILE *stream, const char *format, va_list ap)
Detailed Description
String utility functions header file
Definition in file string_util.h.
Function Documentation
bool any_one_byte_hex_string_to_byte_in_buf (const char * s, Byte * result)
Converts a hex string representing a single byte into its byte value. This is a more lenient version of hhs_to_byte_in_buf(), allowing the value to begin with "0x" or "x", or end with "h". The allowed prefix or suffix is case-insensitive.
Parameters
s pointer to hex string
result pointer to byte in which result will be returned
Returns
true if successful conversion, false if not
Definition at line 780 of file string_util.c.
References hhs_to_byte_in_buf(), str_ends_with(), str_starts_with(), and strdup_uc().
char* bool_repr (int value)
Returns a character string representation of an integer as a boolean value.
Parameters
value value to represent
Returns
"true" or "false"
Definition at line 55 of file string_util.c.
Referenced by devid_ensure_initialized(), fsim_load_control_file(), fsim_load_control_from_gptrarray(), fsim_report_error_table(), is_tracing(), and str_to_int().
char* chars_to_string (const char * start, int len)
Converts a sequence of characters into a (null-terminated) string.
Parameters
start pointer to first character
len number of characters
Returns
newly allocated string, NULL if start was NULL (is this the most useful behavior?)
Definition at line 636 of file string_util.c.
int exactly_matches_any (const char * s, char ** match_list)
Tests if a string exactly matches any string in a null-terminated array of strings. (Null_Terminated_String_Array).
Parameters
s string to test for
match_list null terminated array of pointers to strings
Return values
>= 0 index of matching array entry
-1 no match
Definition at line 190 of file string_util.c.
References matches_by_func(), and streq().
int f0printf (FILE * stream, const char * format, ...)
Extension of fprintf() that allows a NULL stream argument, in which case no output is written.
Parameters
stream if null do nothing
format format string
Returns
result of underlying vfprintf(), or 0 if stream is NULL
Definition at line 1145 of file string_util.c.
Referenced by adl_get_display_by_adlno(), interpret_call_options(), is_tracing(), and rpt_nl().
int f0putc (int c, FILE * stream)
Extension of fputc() that allows a NULL stream argument, in which case no output is written.
Parameters
c character to write
stream if null do nothing
Returns
result of underlying fputs(), or 0 if stream is NULL
Definition at line 1113 of file string_util.c.
int f0puts (const char * msg, FILE * stream)
Extension of fputs() that allows a NULL stream argument, in which case no output is written.
Parameters
msg text to write
stream if null do nothing
Returns
result of underlying fputs(), or 0 if stream is NULL
Definition at line 1129 of file string_util.c.
Referenced by ddc_abort(), is_tracing(), program_logic_error(), and terminate_execution_on_error().
void fhex_dump (FILE * fh, const Byte * data, int size)
Dump a region of memory as hex characters and their ASCII values. Output is written to the location specified by parameter fh.
Parameters
fh where to write output
data start of region to show
size length of region
Definition at line 1088 of file string_util.c.
References fhex_dump_indented().
Referenced by hex_dump().
void fhex_dump_indented (FILE * fh, const Byte * data, int size, int indents)
Dump a region of memory as hex characters and their ASCII values. The output is indented by the specified number of spaces.
Parameters
fh where to write output, if NULL, write nothing
data start of region to show
size length of region
indents number of spaces to indent the output
Definition at line 1031 of file string_util.c.
Referenced by fhex_dump(), and rpt_hex_dump().
Null_Terminated_String_Array g_ptr_array_to_ntsa (GPtrArray * gparray)
Converts a GPtrArray if pointers to strings to a Null_Terminated_String_Array. The underlying strings are referenced, not duplicated.
Parameters
gparray pointer to GPtrArray
Returns
null-terminated array of string pointers
Definition at line 547 of file string_util.c.
Referenced by join_string_g_ptr_array(), and strsplit_maxlength().
void hex_dump (const Byte * data, int size)
Dump a region of memory as hex characters and their ASCII values. Output is written to stdout.
Parameters
data start of region to show
size length of region
Definition at line 1100 of file string_util.c.
References fhex_dump().
Referenced by adl_ddc_get_vcp(), buffer_dump(), and get_x11_edids().
char* hexstring (const unsigned char * bytes, int len)
Converts a sequence of bytes to its representation as a string of hex characters.
Parameters
bytes pointer to bytes
len number of bytes
Returns
pointer to newly allocated hex string
The value returned by this function has been malloc'd. It is the responsibility of the caller to free the memory.
Definition at line 937 of file string_util.c.
Referenced by adl_ddc_get_vcp(), adl_ddc_read_only(), adl_ddc_write_only_with_retry(), adl_ddc_write_read(), adl_ddc_write_read_onecall(), adl_ddc_write_read_with_retry(), adl_ddc_write_read_with_retry_onecall(), call_ADL_Display_DDCBlockAccess_Get(), create_parsed_edid(), get_edid_mfg_id_in_buffer(), and rpt_bytes_as_hex().
char* hexstring2 (const unsigned char * bytes, int len, const char * sepstr, bool uppercase, char * buffer, int bufsz)
Converts a sequence of bytes to its representation as a string of hex characters.
Parameters
bytes pointer to bytes
len number of bytes
sepstr string to separate each 2 hex character pairs representing a byte, if NULL then no separators will be inserted
uppercase if true, use uppercase hex characters, if false, use lower case hex characters
buffer pointer to buffer in which hex string will be returned, if NULL, then a buffer will be allocated
bufsz size of buffer if 0, then a buffer will be allocated
Returns
pointer to hex string
If this function allocates a buffer, it is the responsibility of the caller to free the memory.
Definition at line 971 of file string_util.c.
bool hhc_to_byte_in_buf (const char * p_hh, Byte * converted)
Converts 2 hex characters to their corresponding byte value. The characters need not be null terminated.
Parameters
p_hh pointer to hex characters.
converted pointer go byte in which converted value will be returned
Returns
true if successful conversion, false if s does not point to hex characters
Definition at line 805 of file string_util.c.
References hhs_to_byte_in_buf().
Referenced by store_bytehex_list().
int hhs_to_byte_array (const char * hhs, Byte ** pBa)
Converts a string of hex characters (null terminated) to an array of bytes.
Parameters
hhs string of hex characters
pBa address at which to return pointer to byte array
Return values
>= 0 number of bytes in array,
-1 string could not be converted
If successful, the byte array whose address is returned in pBa has been malloc'd. It is the responsibility of the caller to free it.
Definition at line 877 of file string_util.c.
bool hhs_to_byte_in_buf (const char * s, Byte * result)
Converts a (null terminated) string of 2 hex characters to its byte value.
Parameters
s pointer to hex string
result pointer to byte in which converted value will be returned
Returns
true if successful conversion, false if string does not consist of hex characters, or is not 2 characters in length.
Definition at line 740 of file string_util.c.
Referenced by any_one_byte_hex_string_to_byte_in_buf(), and hhc_to_byte_in_buf().
bool is_abbrev (const char * value, const char * longname, int minchars)
Tests if one string is a valid abbreviation of another.
Parameters
value is this string an abbreviation?
longname unabbreviated value
minchars minimum number of characters that must match
Returns
true/false
Definition at line 88 of file string_util.c.
Referenced by str_starts_with().
char* lsub (const char * s, int ct)
Returns the initial portion of a string
Parameters
s string to process
ct number of characters; if ct is greater than the string length, ct is reduced accordingly
Returns
extracted substring, in newly allocated memory
Definition at line 305 of file string_util.c.
References substr().
int matches_by_func (const char * s, char ** match_list, String_Comp_Func comp_func)
Compares a string to a null-terminated array of strings, using a specified comparison function.
Parameters
s string to test
match_list null terminated array of strings to test against
comp_func comparison function
Return values
>= 0 index of first entry in list for which the comparison function succeeds
-1 no match
Definition at line 168 of file string_util.c.
Referenced by exactly_matches_any(), and starts_with_any().
void ntsa_free (Null_Terminated_String_Array string_array)
Frees a null terminated array of strings. Each string in the array is freed.
Parameters
string_array null terminated array of pointers to strings
Definition at line 481 of file string_util.c.
Referenced by fsim_load_control_from_gptrarray(), and report_udev_device().
int ntsa_length (Null_Terminated_String_Array string_array)
Returns the number of strings in a null terminated array of strings.
Parameters
string_array null terminated array of pointers to strings
Returns
number of strings in the array
Definition at line 495 of file string_util.c.
Referenced by fsim_load_control_from_gptrarray(), ntsa_to_g_ptr_array(), and report_udev_device().
GPtrArray* ntsa_to_g_ptr_array (Null_Terminated_String_Array ntsa)
Converts a Null_Terminated_String_Array to a GPtrArray of pointers to strings. The underlying strings are referenced, not duplicated.
Parameters
ntsa null-terminated array of strings
Returns
newly allocate GPtrArray
Definition at line 530 of file string_util.c.
References ntsa_length().
char* rtrim_in_place (char * s)
Trims trailing whitespace from a string.
Parameters
s string to trim
Returns
s
Definition at line 253 of file string_util.c.
Referenced by rpt_2col().
bool sbuf_append (char * buf, int bufsz, char * sepstr, char * nextval)
Appends a value to a string in a buffer.
Parameters
buf pointer to character buffer
bufsz buffer size
sepstr if non-null, separator string to insert
nextval value to append
Return values
true string was truncated
false normal append
Remarks
Consider allowing the truncation maker, currently "..." to be specified as a parameter.
Definition at line 662 of file string_util.c.
Referenced by connector_type_title(), encoder_type_title(), report_property_value(), and vnt_find_id().
int starts_with_any (const char * s, char ** match_list)
Finds the first entry in a null terminated array of strings that is the initial portion of a specified string.
Parameters
s string to test against
match_list array of prefix strings (null-terminated)
Return values
>= 0 index of matching prefix
-1 not found
Definition at line 204 of file string_util.c.
References matches_by_func(), and str_starts_with().
bool str_all_printable (const char * s)
Are all characters in the string printable?
Parameters
s string to test
Returns
true/false (true if s==NULL)
Definition at line 144 of file string_util.c.
Referenced by execute_shell_cmd_rpt().
bool str_ends_with (const char * value_to_test, const char * suffix)
Tests if string ends with a string.
Parameters
value_to_test value to examine
suffix substring to check for
Returns
true/flase
Remarks
Consider using lib function g_str_suffix() ?? instead
Definition at line 122 of file string_util.c.
References streq().
Referenced by any_one_byte_hex_string_to_byte_in_buf(), execute_shell_cmd_collect(), and execute_shell_cmd_rpt().
bool str_starts_with (const char * value_to_test, const char * prefix)
Tests if string starts with a string.
Parameters
value_to_test value to examine
prefix prefix to check for
Returns
true/flase
Remarks
Consider using lib function g_str_prefix() ?? instead
Definition at line 110 of file string_util.c.
References is_abbrev().
Referenced by any_one_byte_hex_string_to_byte_in_buf(), fsim_report_error_table(), and starts_with_any().
bool str_to_int (const char * sval, int * p_ival)
Converts a string representing an integer to an integer value.
Parameters
sval string representing an integer
p_ival address at which to store integer value
Returns
true if conversion succeeded, false if it failed
Remarks
This function wraps system function strtol(), hiding the ugly details.
Definition at line 698 of file string_util.c.
References bool_repr().
char* strcat_new (char * s1, char * s2)
Concatenates 2 strings into a newly allocated buffer.
Parameters
s1 first string
s2 second string
Returns
newly allocated string
Definition at line 618 of file string_util.c.
char* strdup_uc (const char * s)
Creates an upper case copy of an ASCII string
Arguments:
Parameters
s string to copy
Returns
newly allocated string, NULL if s is NULL
Definition at line 581 of file string_util.c.
Referenced by any_one_byte_hex_string_to_byte_in_buf().
bool streq (const char * s1, const char * s2)
Compares 2 strings for equality, handling nulls
Parameters
s1 first string
s2 second string
Returns
true if the strings match, false if not
Definition at line 71 of file string_util.c.
Referenced by adl_error_name_to_number(), adl_find_display_by_mfg_model_sn(), ddc_error_name_to_number(), errno_name_to_number(), exactly_matches_any(), format_vcp_version_id(), fsim_report_error_table(), report_udev_device(), rpt_bytes_as_hex(), and str_ends_with().
char* strjoin (const char ** pieces, const int ct, const char * sepstr)
Joins an array of strings into a single string, using a separator string.
Parameters
pieces array of strings
ct number of strings
sepstr separator string, if NULL then no separator string
Returns
joined string (null terminated)
The returned string has been malloc'd. It is the responsibility of the caller to free it.
Definition at line 321 of file string_util.c.
Referenced by join_string_g_ptr_array().
Null_Terminated_String_Array strsplit (const char * str_to_split, const char * delims)
Splits a string based on a list of delimiter characters.
Parameters
str_to_split string to be split
delims string of delimiter characters
Returns
null terminated array of pieces
Note: Each character in delims is used as an individual test. The full string is NOT a delimiter string.
Definition at line 374 of file string_util.c.
Referenced by fsim_load_control_from_gptrarray(), and report_udev_device().
Null_Terminated_String_Array strsplit_maxlength (const char * str_to_split, uint16_t max_piece_length, const char * delims)
Splits a string based on a list of delimiter characters. However, no piece is longer than a specified number of characters.
Parameters
str_to_split string to be split
max_piece_length maximum length of each segment
delims string of delimiter characters
Returns
null terminated array of pieces
Note: Each character in delims is used as an individual test. The full string is NOT a delimiter string.
Definition at line 428 of file string_util.c.
References g_ptr_array_to_ntsa().
char* strtrim (const char * s)
Trims leading and trailing whitespace from a string and returns the result in newly allocated memory. It is the caller's responsibility to free this memory. The result string is null terminated.
Parameters
s string to trim (not modified)
Returns
truncated string in newly allocated memory
Definition at line 271 of file string_util.c.
References strtrim_r().
Referenced by fsim_load_control_from_gptrarray().
char* strtrim_r (const char * s, char * buffer, int bufsz)
Trims leading and trailing whitespace from a string and returns the result in a buffer provided by the caller. If the buffer is insufficiently large, the result string is truncated.
The result is always null terminated.
Parameters
s string to trim (not modified)
buffer where to return result
bufsz buffer size
Returns
pointer to truncated string (i.e. buffer)
Definition at line 222 of file string_util.c.
Referenced by strtrim().
char* strupper (char * s)
Converts an ASCII string to upper case. The original string is converted in place.
Parameters
s string to force to upper case
Returns
converted string
Definition at line 563 of file string_util.c.
char* substr (const char * s, int startpos, int ct)
Extracts a substring from a string
Parameters
s string to process
startpos starting position (0 based)
ct number of characters; if ct + startpos is greater than the string length, ct is reduced accordingly
Returns
extracted substring, in newly allocated memory
Definition at line 287 of file string_util.c.
Referenced by lsub().
int vf0printf (FILE * stream, const char * format, va_list ap)
Extension of vfprintf() that allows a NULL stream argument, in which case no output is written.
Parameters
stream if null do nothing
format format string
ap pointer to variable argument list
Returns
result of underlying vfprintf(), or 0 if stream is NULL
Definition at line 1167 of file string_util.c.