ddcutil Internals: util/subprocess_util.h File Reference
subprocess_util.h File Reference
Functions
bool execute_shell_cmd (char *shell_cmd)
bool execute_shell_cmd_rpt (char *shell_cmd, int depth)
GPtrArray * execute_shell_cmd_collect (char *shell_cmd)
bool is_command_in_path (char *cmd)
Detailed Description
Functions to execute shell commands
Definition in file subprocess_util.h.
Function Documentation
bool execute_shell_cmd (char * shell_cmd)
Executes a shell command and writes the output to stdout.
Parameters
shell_cmd command to execute
Returns
true command succeeded false failed, e.g. command not found
Definition at line 124 of file subprocess_util.c.
References execute_shell_cmd_rpt().
GPtrArray* execute_shell_cmd_collect (char * shell_cmd)
Executes a shell command and returns the output as an array of strings.
Parameters
shell_cmd command to execute
Returns
:GPtrArray of response lines if command succeeded NULL if command failed, e.g. command not found
Definition at line 136 of file subprocess_util.c.
References str_ends_with().
Referenced by is_command_in_path().
bool execute_shell_cmd_rpt (char * shell_cmd, int depth)
Executes a shell command and writes the output to the current report destination or to stdout.
Parameters
shell_cmd command to execute
depth logical report indentation depth, if < 0, write to stdout
Returns
true command succeeded false failed, e.g. command not found
Definition at line 51 of file subprocess_util.c.
References str_all_printable(), and str_ends_with().
Referenced by execute_shell_cmd().
bool is_command_in_path (char * cmd)
Tests if a command is found in path
Parameters
cmd command name
Returns
true/false
TODO: Check that actually executable, e.g. could be in /sbin and not running privileged
Definition at line 193 of file subprocess_util.c.
References execute_shell_cmd_collect().