ddcutil Internals: util/timestamp.c File Reference
timestamp.c File Reference
#include "timestamp.h"
Functions
long cur_realtime_nanosec ()
void show_timestamp_history ()
long elapsed_time_nanosec ()
char * formatted_elapsed_time ()
Variables
bool tracking_timestamps = false
Detailed Description
Timestamp Management
Definition in file timestamp.c.
Function Documentation
long cur_realtime_nanosec ()
Returns the current value of the realtime clock in nanoseconds.
Returns
timestamp, in nanoseconds
Remarks
If debugging timestamp generation, the timestamp is remembered.
Definition at line 62 of file timestamp.c.
References tracking_timestamps.
Referenced by elapsed_time_nanosec(), and init_execution_stats().
long elapsed_time_nanosec ()
Returns the elapsed time in nanoseconds since the start of program execution.
The first call to this function marks the start of program execution and returns 0.
Returns
nonoseconds since start of program execution
Definition at line 115 of file timestamp.c.
References cur_realtime_nanosec().
Referenced by formatted_elapsed_time().
char* formatted_elapsed_time ()
Returns the elapsed time since start of program execution as a formatted, printable string.
The string is built in an internal buffer and is valid until the next call of this function.
Returns
formatted elapsed time
Definition at line 134 of file timestamp.c.
References elapsed_time_nanosec().
Referenced by is_tracing().
void show_timestamp_history ()
Reports history of generated timestamps
Remarks
This is a debugging function.
Definition at line 85 of file timestamp.c.
References tracking_timestamps.
Variable Documentation
bool tracking_timestamps = false
For debugging timestamp generation, maintain a timestamp history.
Definition at line 45 of file timestamp.c.
Referenced by cur_realtime_nanosec(), and show_timestamp_history().