ddcutil Internals: util/udev_util.h File Reference
udev_util.h File Reference
Data Structures
struct Udev_Device_Summary
struct Usb_Detailed_Device_Summary
struct Udev_Usb_Devinfo
Functions
void free_udev_device_summaries (GPtrArray *summaries)
GPtrArray * summarize_udev_subsystem_devices (char *subsystem)
void report_udev_device (struct udev_device *dev, int depth)
void probe_udev_subsystem (char *udev_class, bool show_usb_parent, int depth)
void free_usb_detailed_device_summary (Usb_Detailed_Device_Summary *devsum)
void report_usb_detailed_device_summary (Usb_Detailed_Device_Summary *devsum, int depth)
Usb_Detailed_Device_Summary * lookup_udev_usb_device_by_devname (char *devname)
void report_udev_usb_devinfo (struct udev_usb_devinfo *dinfo, int depth)
Udev_Usb_Devinfo * get_udev_usb_devinfo (char *subsystem, char *simple_devname)
Detailed Description
UDEV utility functions
Definition in file udev_util.h.
Function Documentation
void free_udev_device_summaries (GPtrArray * summaries)
Destroys a GPtrArray of Udev_Device_Summary
Parameters
summaries pointer to GPtrArray of summaries
Definition at line 64 of file udev_util.c.
References Udev_Device_Summary::devpath, Udev_Device_Summary::marker, Udev_Device_Summary::sysattr_name, and Udev_Device_Summary::sysname.
void free_usb_detailed_device_summary (Usb_Detailed_Device_Summary * devsum)
Frees a Usb_Detailed_Device_Summary. All underlying memory is released.
Parameters
devsum pointer to Usb_Detailed_Device_Summary
Definition at line 217 of file udev_util.c.
References Usb_Detailed_Device_Summary::busnum_s, Usb_Detailed_Device_Summary::devname, Usb_Detailed_Device_Summary::devnum_s, Usb_Detailed_Device_Summary::marker, Usb_Detailed_Device_Summary::product_id, Usb_Detailed_Device_Summary::product_name, Usb_Detailed_Device_Summary::vendor_id, and Usb_Detailed_Device_Summary::vendor_name.
Referenced by lookup_udev_usb_device_by_devname().
Udev_Usb_Devinfo* get_udev_usb_devinfo (char * subsystem, char * simple_devname)
Use UDEV to get the bus and device numbers for a USB device
Parameters
subsystem device subsystem, e.g. "usbmisc"
simple_devname simple device name, e.g. "hiddev"
Returns
pointer to Udev_Usb_Devinfo containing result
NULL if not found
Adapted from UDEV sample code.
Definition at line 488 of file udev_util.c.
References Udev_Usb_Devinfo::busno, Udev_Usb_Devinfo::devno, and report_udev_usb_devinfo().
Usb_Detailed_Device_Summary* lookup_udev_usb_device_by_devname (char * devname)
Look up information for a device name. The expected use in in error messages.
Parameters
devname device name, e.g. /dev/usb/hiddev3
Returns
pointer to newly allocated Usb_Detailed_Device_Summary struct, NULL if not found
Definition at line 263 of file udev_util.c.
References Usb_Detailed_Device_Summary::busnum_s, Usb_Detailed_Device_Summary::devname, Usb_Detailed_Device_Summary::devnum_s, free_usb_detailed_device_summary(), Usb_Detailed_Device_Summary::product_id, Usb_Detailed_Device_Summary::product_name, rpt_vstring(), Usb_Detailed_Device_Summary::vendor_id, and Usb_Detailed_Device_Summary::vendor_name.
void probe_udev_subsystem (char * subsystem, bool show_usb_parent, int depth)
Reports on all devices in a UDEV subsystem
Parameters
subsystem subsystem name, e.g. "usbmisc"
show_usb_parent include reports on parent devices
depth logical indentation depth
Remarks
Adapted from USB sample code
Definition at line 372 of file udev_util.c.
References report_udev_device(), and rpt_vstring().
void report_udev_device (struct udev_device * dev, int depth)
Report on a single UDEV device
Parameters
dev pointer to struct udev_device to report
depth logical indentation depth
Definition at line 130 of file udev_util.c.
References Usb_Detailed_Device_Summary::marker, ntsa_free(), ntsa_length(), rpt_structure_loc(), rpt_vstring(), streq(), and strsplit().
Referenced by probe_udev_subsystem().
void report_udev_usb_devinfo (struct udev_usb_devinfo * dinfo, int depth)
Reports on a struct udev_usb_devinfo.
Parameters
dinfo pointer to struct
depth logical indentation depth
Definition at line 470 of file udev_util.c.
References rpt_structure_loc(), and rpt_vstring().
Referenced by get_udev_usb_devinfo().
void report_usb_detailed_device_summary (Usb_Detailed_Device_Summary * devsum, int depth)
Reports a Usb_Detailed_Device_Summary instance.
Parameters
devsum pointer to Usb_Detailed_Device_Summary
depth logical indentation depth
Definition at line 237 of file udev_util.c.
References Usb_Detailed_Device_Summary::busnum_s, Usb_Detailed_Device_Summary::devname, Usb_Detailed_Device_Summary::devnum_s, Usb_Detailed_Device_Summary::marker, Usb_Detailed_Device_Summary::product_id, Usb_Detailed_Device_Summary::product_name, rpt_str(), rpt_structure_loc(), Usb_Detailed_Device_Summary::vendor_id, and Usb_Detailed_Device_Summary::vendor_name.
GPtrArray* summarize_udev_subsystem_devices (char * subsystem)
Queries UDEV to obtain summaries of each device in a subsystem.
Parameters
subsystem subsystem name, e.g. "i2c-dev"
Returns
GPtrArray of Udev_Device_Summary
Definition at line 85 of file udev_util.c.