ddcutil Internals: base/vcp_version.c File Reference
vcp_version.c File Reference
#include "util/data_structures.h"
#include "util/string_util.h"
#include "base/core.h"
#include "base/vcp_version.h"
Functions
bool vcp_version_le (DDCA_MCCS_Version_Spec v1, DDCA_MCCS_Version_Spec v2)
char * format_vcp_version_id (DDCA_MCCS_Version_Id version_id)
Detailed Description
VCP/MCCS Version Specification
Note that MCCS (VCP) versioning forms a directed graph, not a linear ordering.
The v3.0 spec is an extension of v2.1, not v2.2. Both v3.0 and v2.2 are successors to v2.1.
                 -- v3.0
                |
v1.0—v2.0-— v2.1 | – v2.2
Definition in file vcp_version.c.
Function Documentation
char* format_vcp_version_id (DDCA_MCCS_Version_Id version_id)
Returns a DDCA_MCCS_Version_Id in a form suitable for display, e.g. "2.0".
Parameters
version_id version id value
Returns
value in external form.
Definition at line 165 of file vcp_version.c.
References DDCA_V10, DDCA_V20, DDCA_V21, DDCA_V22, DDCA_V30, DDCA_VANY, DDCA_VNONE, DDCA_VUNK, DDCA_MCCS_Version_Spec::major, PROGRAM_LOGIC_ERROR, streq(), vnt_name(), and vnt_title().
bool vcp_version_le (DDCA_MCCS_Version_Spec v1, DDCA_MCCS_Version_Spec v2)
Checks if one DDCA_MCCS_Version_Spec is less than or equal to another.
Parameters
v1 first version spec
v2 second version spec
Return values
true v1 is <= v2
false v1 > v2
Remarks
Aborts if an attempt is made to compare v2.2 with v3.0
Will require modification if a new spec appears
Definition at line 103 of file vcp_version.c.
References DDCA_V10, DDCA_V20, DDCA_V21, DDCA_V22, DDCA_V30, DDCA_VNONE, DDCA_MCCS_Version_Spec::major, vcp_version_le(), VNT, and VNT_END.
Referenced by vcp_version_le().